### ISSUE TITLE
how to create table testrun  events and user_count

### ISSUE THREAD

**Issue by FANHIDE** [SvenskaSpel/locust-plugins#1]
When i use TimescaleListener, i found that the listeners_timescale_table.sql file only contains create table request. 
There is my question:
how to create table testrun   events  and user_count

thx!

**Comment by cyberw** [comment]
hi! I added the full schema now: https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/timescale_schema.sql

Let me know if it works or not :)

**Comment by FANHIDE** [comment]
thx!I will try later~

**Comment by FANHIDE** [comment]
hi, there is a new question when i want to insert into testrun table.
![image](https://user-images.githubusercontent.com/29531967/74215728-01ce4480-4cdd-11ea-8a22-4fa484e04088.png)
the _changeset_guid = 'lsls'

**Comment by cyberw** [comment]
Maybe you need to add timescale to your config? https://github.com/timescale/timescaledb/issues/562

**Comment by FANHIDE** [comment]
I use the docker image to start the timescale，the image is timescale/timescaledb:latest-pg10

 I just check the config :
![image](https://user-images.githubusercontent.com/29531967/74216990-144a7d00-4ce1-11ea-99b6-95fefd9e207a.png)
I try to restart the docker container , create the table again.
But it doesn't work

**Comment by cyberw** [comment]
Try running it from cli and add the update  command listed here first https://docs.timescale.com/latest/using-timescaledb/troubleshooting

**Comment by FANHIDE** [comment]
thx! I solved this just now~
