### ISSUE TITLE
Is it necessary exclusive control on CSVreader?

### ISSUE THREAD

**Issue by nichero-h** [SvenskaSpel/locust-plugins#103]
Hi,

[examples/csvreader_ex.py](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/csvreader_ex.py)  does not use gevent.lock or threading.Lock.
Is exclusive control unnecessary?

Thanks in advance.

**Comment by cyberw** [comment]
Yes. There is only one (asyncronous) thread in a gevent application such as Locust, so normally it is not needed.

**Comment by nichero-h** [comment]
Thank you for reply.
