### ISSUE TITLE
Question: Adding custom information to locust timescale logs

### ISSUE THREAD

**Issue by nixpix** [SvenskaSpel/locust-plugins#107]
Hi.
I just recently found this repo and set it up internally for my team.
I am not that experienced with python and locust, and I am wondering how I could add additional information to the logs that are persisted in the timescaledb.

For example, I have a request and I want to add a column in the "request" table where I would log an ID that I send in the request. 
The current entry in the table looks like:
|time|run_id|exception|greenlet_id|loadgen|name|request_type|response_length|response_time|success|testplan|pid|context|url|
|----|------|---------|-----------|-------|----|------------|---------------|-------------|-------|--------|---|-------|---|
|2022-12-02 13:41:32.984 +0100|2022-12-02 13:41:26.309 +0100||3|ef8e97742c42|PWS - /v5/books|GET|184500|83.38429200011888|1|./|7|{}|https://xxxxxxxxxxxxx.net/v5/books|

I would like to add a column where I could send additional data from locust to be logged there.

**Comment by cyberw** [comment]
Hi! Adding a custom column is somewhat complicated, but adding a field in the context object is super-easy - just add it to the request, like this:

`self.client.post("/", context={"my_id": 1234}`

**Comment by cyberw** [comment]
Or you can do `self.context = {"my_id": 1234}` before the request and it will be added to all of them.

**Comment by nixpix** [comment]
Thanks, @cyberw that's great info.

If I understand correctly, this is for adding context before sending a request.
How could I apply some information that I got from the response to the request that is logged?

For example:
I get a specific string in the response for a request, and I want to log that string for that request.
So that I can filter all requests based on the specific string in their responses.

**Comment by cyberw** [comment]
You can do alter the context after the fact, like this:

   with self.client.request(
            "GET",
            ...
            catch_response=True,
        ) as resp:
             resp.request_meta["context"]["request_id"] = resp.json()["requestId"]

**Comment by nixpix** [comment]
Awesome.
Thank you for the quick replies. This helps me a lot.

I'll close the issue since my questions have been answered.
