### ISSUE TITLE
TimescaleListener - Failed to write user count to Postgresql: FeatureNotSupported

### ISSUE THREAD

**Issue by StasGrishaev** [SvenskaSpel/locust-plugins#11]
Hi there @cyberw !
I spent quite a bit of time trying to add your plugin - TimescaleListener to display graphs in Grafana. and I am tightly stuck on an INSERT table
what i tried:
- creating a new PG database via pgAdmin and from the command line via psql (9 and 11 versions with the corresponding timescale version of the plugin) from your dump listeners_timescale_table.sql, after restarting the PG server (judging by the logs everything was created successfully)
screenshot error stack, selected text - values for INSERT operation

What am I missing and what can I try?

![image](https://user-images.githubusercontent.com/19959547/82480649-c5c92d80-9adc-11ea-98c5-061959518d46.png)

**Comment by cyberw** [comment]
Did you install the timescale extension correctly? Try googling the message: "make sure the timescaledb extension has been preloaded"

Also, I notice you are on windows. While it could work, you are pretty much on your own there :-/

**Comment by StasGrishaev** [comment]
@cyberw thanks for quick response !
> Did you install the timescale extension correctly?
yeah, i believe so.
how do you suggest apply dump from listeners_timescale_table.sql ? by psql CLI or by pgAdmin web interface ?

**Comment by cyberw** [comment]
CLI or web interface shouldnt really matter. Have you done these steps: https://github.com/timescale/timescaledb/issues/550#issuecomment-396582645 ?

**Comment by ludeknovy** [comment]
I run into this issue as well. 

my postgres.conf contains `shared_preload_libraries= 'timescaledb'` entry 
and `select * from pg_extension` returns `timescaledb`.

**Comment by cyberw** [comment]
Hmm.. Lots of people seem to be having this issue with timescale (not just users of locust-plugins). Have you checked: https://docs.timescale.com/latest/using-timescaledb/troubleshooting

**Comment by StasGrishaev** [comment]
> CLI or web interface shouldnt really matter. Have you done these steps: timescale/timescaledb#550 (comment) ?

yep. 

@ludeknovy are you also on Windows ?

**Comment by cyberw** [comment]
maybe @StasGrishaev was on to something?

> Error updating TimescaleDB when using a third-party PostgreSQL admin tool.
> 
> The update command ALTER EXTENSION timescaledb UPDATE must be the first command executed upon connection to a database. Some admin tools execute command before this, which can disrupt the process. It may be necessary for you to manually update the database with psql. See our update docs for details.

**Comment by ludeknovy** [comment]
@StasGrishaev no, I was running timescale in docker

**Comment by StasGrishaev** [comment]
alright guys, i made it ! the thing is a triggers - https://github.com/timescale/timescaledb/issues/1381
after i manually disabled these triggers through pgAdmin on request, testrun and user_count tables ( example on screenshot ) everything works as a charm. @cyberw thanks again for great listener !

![image](https://user-images.githubusercontent.com/19959547/82543685-a07c0400-9b5c-11ea-8056-f20d617147c8.png)

**Comment by cyberw** [comment]
> alright guys, i made it ! the thing is a triggers - [timescale/timescaledb#1381](https://github.com/timescale/timescaledb/issues/1381)
> after i manually disabled these triggers through pgAdmin in request, testrun and user_count tables ( example on screenshot ) everything started to work. @cyberw thanks again for great listener !
> 
> ![image](https://user-images.githubusercontent.com/19959547/82543685-a07c0400-9b5c-11ea-8056-f20d617147c8.png)
> 
> @cyberw it would be nice to add this info to documentation or maybe directly to sql dump file as a comment, how do you think ?

I think that is a great idea. I think the documentation is the right place to put it (as the dump might need to be regenerated at some point). Maybe we should also reference this ticket.

Can you do it and file a PR? It would be really appreciated :) Or I can do it.

**Comment by StasGrishaev** [comment]
> Can you do it and file a PR? It would be really appreciated :) Or I can do it.

sure, i will do it. also close the issue 👍

**Comment by ludeknovy** [comment]
The triggers can be removed by running this query:
```
DROP TRIGGER ts_insert_blocker ON public.request
```

**Comment by ludeknovy** [comment]
@cyberw may I ask whats the purpose of using timescaleDB if you dont use hypertable(s)?
When I import `timescale_schema.sql` and run `select * from _timescaledb_catalog.hypertable` it returns 0 records. Do I miss something?

**Comment by cyberw** [comment]
requests is meant to be a hypertable. Maybe the fix suggested by Stas is wrong?

**Comment by ludeknovy** [comment]
@cyberw Well, I did not find any other way to fix the FeatureNotSupported issue other than removing the triggers as suggested by Stas. Actually the insert block triggers are expected to happen as described in one of the issue in timescale repo. As per [timescale](https://docs.timescale.com/latest/using-timescaledb/backup#pg_dump-pg_restore) docs, after importing the backup you are supposed to recreate the hypertables. But again when I try to run `SELECT create_hypertable('request', 'time')` it fails because of `No function matches the given name and argument types.`

I have the timescale db extension installed according to `SELECT * FROM pg_extension`.

**Comment by cyberw** [comment]
Sorry, I'm not very good at timescale setup so I'm not sure how to help. All the tables are supposed to be hypertables though.

```
postgres=# select * from _timescaledb_catalog.hypertable;
 id | schema_name | table_name | associated_schema_name | associated_table_prefix | num_dimensions | chunk_sizing_func_schema |  chunk_sizing_func_name  | chunk_target_size
----+-------------+------------+------------------------+-------------------------+----------------+--------------------------+--------------------------+-------------------
  2 | public      | request    | _timescaledb_internal  | _hyper_2                |              1 | _timescaledb_internal    | calculate_chunk_interval |                 0
  3 | public      | testrun    | _timescaledb_internal  | _hyper_3                |              1 | _timescaledb_internal    | calculate_chunk_interval |                 0
  4 | public      | user_count | _timescaledb_internal  | _hyper_4                |              1 | _timescaledb_internal    | calculate_chunk_interval |                 0
```

**Comment by ludeknovy** [comment]
This is the outcome on your local db after importing the dump? Or is this the state of your db where from which you made the actual dump?

**Comment by cyberw** [comment]
this is the state of my db from which I made the dump. Gimme a sec and I'll try making a new dump just to try that...

**Comment by ludeknovy** [comment]
Thats what I thought! Try to make it please according to https://docs.timescale.com/latest/using-timescaledb/backup#pg_dump-pg_restore

**Comment by cyberw** [comment]
This file is not actually zipped I just renamed it for github to accept it.

[locust.bak.zip](https://github.com/SvenskaSpel/locust-plugins/files/5819435/locust.bak.zip)

**Comment by ludeknovy** [comment]
When I tried to restore the locust.bak I got: `pg_restore: warning: errors ignored on restore: 580` :/

Could you please try `pg_dump -s -d old_db --table conditions -N _timescaledb_internal | \
  grep -v _timescaledb_internal > schema.sql` for each table?

**Comment by cyberw** [comment]
[tables.zip](https://github.com/SvenskaSpel/locust-plugins/files/5820333/tables.zip)

**Comment by cyberw** [comment]
timescale documentation mentioned that restoring on a different version might cause issues. I'm on version 1.3.1.

**Comment by ludeknovy** [comment]
The restore did not work for me :/. I've created new schema.sql and it works out of the box in docker.

[schema.sql.zip](https://github.com/SvenskaSpel/locust-plugins/files/5820970/schema.sql.zip)

**Comment by cyberw** [comment]
Looks like that docker image is using timescale version 2.0.0-rc4, which is probably not compatible with my version (1.3.1)
