### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by femo1de** [SvenskaSpel/locust-plugins#110]
Installation of the current version fails (Win 11 with Python 3.11, C++ Build Tools are installed) with the message 

`Cannot open include file: librdkafka/rdkafka.h`

![image](https://user-images.githubusercontent.com/90273092/210834760-973dae65-e7be-4893-a885-8dba37a375f8.png)

**Comment by vuongphamaioz** [comment]
Hi,

I also faced this issue and followed this https://github.com/confluentinc/confluent-kafka-python/issues/1452#issuecomment-1335494953 to resolve it.
If you do not use Docker, remove `RUN` command.

**Comment by cyberw** [comment]
confluent-kafka 2.0.2 has now been released and has pre-built wheels for 3.11!
