### ISSUE TITLE
NameError: name 'error' is not defined

### ISSUE THREAD

**Issue by dmitry-rozhd** [SvenskaSpel/locust-plugins#112]
Greetings!

Recently I've got the issue while playing with your brilliant playwright locust plugin:

> locust_plugins/users/playwright.py", line 175, in pwwrapFunc  exception=error, NameError: name 'error' is not defined

<here goes my code which resulted in a timeout error>
playwright._impl._api_types.TimeoutError: Timeout 90000ms exceeded.
=========================== logs ===========================
waiting for navigation until 'load'
============================================================

<here goes the issue I'm asking you to address>

During handling of the above exception, another exception occurred:

'Traceback (most recent call last):
File %redacted%/venv_locust/lib/python3.10/site-packages/locust/user/task.py", line 347, in run
    self.execute_next_task()
 File %redacted%/venv_locust/lib/python3.10/site-packages/locust/user/task.py", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File %redacted%/venv_locust/lib/python3.10/site-packages/locust/user/task.py", line 493, in execute_task
    task(self.user)
  File %redacted%/venv_locust/lib/python3.10/site-packages/locust_plugins/users/playwright.py", line 57, in wrapFunc
    raise e
  File %redacted%/venv_locust/lib/python3.10/site-packages/locust_plugins/users/playwright.py", line 175, in pwwrapFunc
    exception=error,
NameError: name 'error' is not defined'

As you see, it refers to https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/users/playwright.py, line 175.

I have a feeling that 'exception=error' should be 'exception=e'.

Can you please check this? 

Many thanks for considering my request!

**Comment by cyberw** [comment]
fixed
