### ISSUE TITLE
Locust exits 1 when percentage of failures under threshold set by --check-fail-ratio

### ISSUE THREAD

**Issue by eightycolumns** [SvenskaSpel/locust-plugins#113]
To illustrate the issue, I ran `python -m locust --check-fail-ratio 1.00 --headless --locustfile locustfile.py --logfile locust.log --loglevel DEBUG --run-time 15s --users 1` with the following `locustfile.py`:

```
from locust import HttpUser, between, task
import locust_plugins
import urllib3

urllib3.disable_warnings()

class ServiceUser(HttpUser):
    host = "https://api.publicapis.org/"
    wait_time = between(4, 8)
    initial_response = None

    @task
    def get_entries(self):
        route = "entries"

        with self.client.get(route, verify=False, catch_response=True) as response:
            if not self.initial_response:
                self.initial_response = response
                response.failure("Failing first test just for the heck of it")
```

This guarantees one failure but ensures that the percentage of failures remains under the threshold of 100% set by `--check-fail-ratio`.

The resulting `locust.log` contains
```
[2023-02-15 17:28:56,582] NW221518/DEBUG/root: CHECK SUCCESSFUL: fail ratio was 50.00% (threshold 100.00%)
[2023-02-15 17:28:56,582] NW221518/DEBUG/root: CHECK SUCCESSFUL: total rps was 0.2 (threshold 0.0)
[2023-02-15 17:28:56,582] NW221518/INFO/locust.main: Shutting down (exit code 1)
```

The exit code of 1 causes unanticipated load testing failures in CI.

This can be resolved by adding `--exit-code-on-error 0`, but [the absence of this flag](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/cmd_line_examples.sh#L6) in the examples suggests that it wasn't intended to be necessary.

It could also be resolved by adding two lines to the end of the quitting listener `do_checks()` in [\_\_init\_\_.py](https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/__init__.py), like
```
@events.quitting.add_listener
def do_checks(environment, **_kw):
    if isinstance(environment.runner, WorkerRunner):
        return

    stats = environment.runner.stats.total
    fail_ratio = stats.fail_ratio
    total_rps = stats.total_rps
    avg_response_time = stats.avg_response_time

    opts = environment.parsed_options
    check_rps = opts.check_rps
    check_fail_ratio = opts.check_fail_ratio
    check_avg_response_time = opts.check_avg_response_time

    if fail_ratio > check_fail_ratio:
        logging.info(f"CHECK FAILED: fail ratio was {(fail_ratio*100):.2f}% (threshold {(check_fail_ratio*100):.2f}%)")
        environment.process_exit_code = 3
    else:
        logging.debug(
            f"CHECK SUCCESSFUL: fail ratio was {(fail_ratio*100):.2f}% (threshold {(check_fail_ratio*100):.2f}%)"
        )

    if total_rps < check_rps:
        logging.info(f"CHECK FAILED: total rps was {total_rps:.1f} (threshold {check_rps:.1f})")
        environment.process_exit_code = 3
    else:
        logging.debug(f"CHECK SUCCESSFUL: total rps was {total_rps:.1f} (threshold {check_rps:.1f})")

    if check_avg_response_time > 0:
        if avg_response_time > check_avg_response_time:
            logging.info(
                f"CHECK FAILED: avg response time was {avg_response_time:.1f} (threshold {check_avg_response_time:.1f})"
            )
            environment.process_exit_code = 3
        else:
            logging.debug(
                f"CHECK SUCCESSFUL: avg response time was {avg_response_time:.1f} (threshold {check_avg_response_time:.1f})"
            )

        if not environment.process_exit_code:
            environment.process_exit_code = 0
```
            
Then locust's [shutdown()](https://github.com/locustio/locust/blob/master/locust/main.py#L420-L423) wouldn't check `len(runner.errors)` and set `code` to 1.

Or, if the expectation is that `--exit-code-on-error 0` be added to avoid this issue, the [docs](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/cmd_line_examples.sh#L6) could be updated to show its use.

What do you think?

**Comment by cyberw** [comment]
—check-fail-ratio should implicitly set —exit-code-on-error to zero. PR welcome!

**Comment by eightycolumns** [comment]
PR #114 opened.

An alternative approach could be to subclass the default `store` action to store the value of `check_fail_ratio` and to set `exit_code_on_error` to 0 at the same time, like
```
import argparse

class CheckFailRatioStoreAction(argparse._StoreAction):
    def __call__(self, parser, namespace, values, option_string=None):
        setattr(namespace, self.dest, values)
        setattr(namespace, "exit_code_on_error", 0)
```
        
And then
```
checks.add_argument(
    "--check-fail-ratio",
    action=CheckFailRatioStoreAction,
    type=float,
    help="Ratio of failed requests (0.0-1.0)",
    env_var="LOCUST_CHECK_FAIL_RATIO",
    default=1.0,
)
```

But it doesn't look like it's important for `--check-fail-ratio` to set `--exit-code-on-error` to 0 _immediately_ when args are parsed, so the approach in #114 seemed preferable to me, since it doesn't require subclassing a private class.

**Comment by cyberw** [comment]
fixed
