### ISSUE TITLE
Create plugin (extension) to change file name of automated html report with timestamp and locustfile name

### ISSUE THREAD

**Issue by wallacekabum** [SvenskaSpel/locust-plugins#115]
I needed locust to save the name of the automated HTML report files at runtime with timestamp+locustfilename.html.
I created a feature where it extends the locust and directly changes the name of the html_file when it comes with the arg --html=rename.html
So it will overwrite the name rename.html to <timestamps>_<locustfile>.html
This way I can organize and save all executions by time and by suite.

**Comment by cyberw** [comment]
Not really a good fit for locust-plugins. Perhaps you can just write a few lines of code in a function tied to the `quitting` event handler?

**Comment by wallacekabum** [comment]
Agree, it is something that is not too complex. I'm thinking more in terms of extension and plugin. Facilitate this option for people who do not have full command of the tool. For example, this CSV reading lib with little code is also something interesting, which didn't need a lot of code. https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/csvreader.py

sorry my english is not very good. I'm using Google Translate to help
