### ISSUE TITLE
Can't send a message

### ISSUE THREAD

**Issue by Elvintest** [SvenskaSpel/locust-plugins#118]
Hello, i'm trying to send a message through socket locust plugin, it connects correctly, but when i'm trying to send a message(following server specification) i get error cause "m" is None. Going deeper to code i can see that there'is some regex for messages
```
    def send(self, body, name=None, context={}):
        if not name:
            if body == "2":
                name = "2 heartbeat"
            else:
                # hoping this is a subscribe type message, try to detect name
                m = re.search(r'(\d*)\["([a-z]*)"', body)
                assert m is not None
                code = m.group(1)
                action = m.group(2)
                url_part = re.search(r'"url": *"([^"]*)"', body)
                assert url_part is not None
                url = re.sub(r"/[0-9_]*/", "/:id/", url_part.group(1))
                name = f"{code} {action} url: {url}"
```
My message has this view:
```
{
    "control": {
        "name": "token",
        "param": {
            "token": "xxxxxxx",
            "userId": "some uuid"
        }
    },
    "seq": 0,
    "ack": 0
}
```
So i don't understand which numbers are ment in regex my message went through (re.search(r'(\d*)). Can you clarify this logic for me?

**Comment by cyberw** [comment]
It is intended for payloads that look like this. They were used in my particular web page, and seem to be common in socket.io apps, but in your case you may want to pass `name="token"` to avoid auto detection alltogether.

![image](https://user-images.githubusercontent.com/1134328/230941749-440483c9-2d2c-4128-afa0-b1049df573db.png)

**Comment by Elvintest** [comment]
Yes, what you have shown is a classic format for socketIO specification, i have a deal with just wss socket(no IO). It doesn't need to get 2 as ping and doesnt't send 3 as pong, it has its own specification, basically it needs json format message as i described above. Is you plugin suitable for me at all? I have doubts now cause it doesn't take just raw message to send it but has some processing it. Btw examples for messages i deal with:
![image](https://user-images.githubusercontent.com/61495894/230948833-a8ad6be9-3068-4457-b780-da350506cba5.png)

**Comment by cyberw** [comment]
You can easily overload the send method as needed. Something like

```
class MyUser(SocketIOUser):
       def send(self, body, name=None, context={}):
             super().send(body, name=json.loads(body).keys()[0], context)
```

But if that is not a good fit for you then you can absolutely write your own.

**Comment by Elvintest** [comment]
Thanks, i created a class based on yours and trying to adjust it, can i ask couple more questions: the first i don't see how yu stop socket connection:
```
    def receive_loop(self):
        while True:
            message = self.ws.recv()
            logging.debug(f"WSR: {message}")
            self.on_message(message)
```
seems like it works always, and i'm not sure if i understand where you get response time:
```
        self.environment.events.request.fire(
            request_type="WSR",
            name=name,
            response_time=response_time,
            response_length=len(message),
            exception=None,
            context=self.context(),
        )
```
Seems you get it somehow from response message, i don't have this option. Any advice how to measure response time for getting message?

**Comment by cyberw** [comment]
> i don't see how yu stop socket connection:

Yea... I never got around to implementing that :) I didnt even save the greenlet. But with the change I just pushed (https://github.com/SvenskaSpel/locust-plugins/commit/0063fa31d89eaa0547482239122cf23e3b32b9df) you can kill the receive loop:

```
self.ws_greenlet.kill()
```

And then close the socket

```
self.ws.close()
```

> Any advice how to measure response time for getting message?

Web socket messages are server-initiated so it is not to measure response time. 

In my special case the payload contains a timestamp (specifying when the message was originally created in some source system), and pretend that is the time that was the request "start time". If your system provides such a timestamp in the payload (or you can feed that data into your payloads and have them piggyback in your payload) then you can adjust approach, but if not then there is really no logical response time to measure.
