### ISSUE TITLE
GKE Worker2 pod Exception - Timescale object has no attribure '_run_id'

### ISSUE THREAD

**Issue by kuttysh** [SvenskaSpel/locust-plugins#122]
I am running Locust on GKE  distributed with one master and 2 workers (All the master and Worker pods are in the same cluster and Namespace)

During the run one worker is able to write data to Timescale DB with out any exections and other worker failed to write to TimescaleDB with exception Timescale object has no attribure '_run_id'

`[2023-05-11 20:18:17,988] worker2/ERROR/root: Uncaught exception in event handler: 
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/locust/event.py", line 40, in fire
    handler(**kwargs)
  File "/opt/venv/lib/python3.10/site-packages/locust_plugins/listeners.py", line 240, in on_request
    "run_id": self._run_id,
AttributeError: 'Timescale' object has no attribute '_run_id'`

With one worker node this is working perfectly.  When I add more then one worker I got this error.  Appriciate your help.

**Comment by cyberw** [comment]
My guess is that the run id is not sent to your second worker, because it wasn't connected when the test started. 

What if you specify `--expect-workers 2` on the master side, so that the test is not started until both have connected?

**Comment by kuttysh** [comment]
if i add `--expect-workers 2` on the master side it is workking good. Thank you !
