### ISSUE TITLE
Run playwright_ex.py but it does not seem to do anything

### ISSUE THREAD

**Issue by jnjgomez10** [SvenskaSpel/locust-plugins#124]
I ran [playwright_ex.py](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/playwright_ex.py) on my machine but I am not seeing any statistics.  Am I missing anything? 

![image](https://github.com/SvenskaSpel/locust-plugins/assets/116907590/fa41482c-116e-4862-9c9a-e1b3ae7d15f3)

**Comment by cyberw** [comment]
Try running it in debug, so that you see the browser and what it is doing.

**Comment by jnjgomez10** [comment]
Sorry but how can I run it in debug mode?

**Comment by cyberw** [comment]
See https://docs.locust.io/en/stable/running-in-debugger.html

**Comment by Mateo13** [comment]
I see the same thing when trying to run playwright_ex.py on Windows.  I verified playwright is working in my setup and a basic locust script runs.  I can run it in a Linux environment.
