### ISSUE TITLE
How do I run websocketUser and httpUser together

### ISSUE THREAD

**Issue by luqy** [SvenskaSpel/locust-plugins#126]
I define a websocketUser, but I want to run both in the task, but I get an error
![image](https://github.com/SvenskaSpel/locust-plugins/assets/42463694/66acdcd4-ed4a-485f-b629-d129adaa7afb)

**Comment by cyberw** [comment]
Combine User types using multiple inheritance. Dont put Users in `tasks`

**Comment by luqy** [comment]
class httplist(TaskSet):
    pass
class webslist(Taskset):
    pass
class listUser(HttpUser,WebsocketUser):
    tasks={httplist:1,webslist:1}
    
    An error will be generated：
    AttributeError: 'webslist' object has no attribute 'connect'
    
    so,Can I only write it as
    class Userlist(HttpUser,WebsocketUser):
    @task
    def httplist(self):
        pass
    def webslist(self):
        pass
        
        This can be run

**Comment by luqy** [comment]
I see, thank you

**Comment by luqy** [comment]
I see, thank you
