### ISSUE TITLE
Locust Playwright Webkit support and Chrome extension support

### ISSUE THREAD

**Issue by vnbal** [SvenskaSpel/locust-plugins#127]
Running locust with Playwright. Facing issue in adding extension in the browser. Enabled Headless as false during the execution and trying to configure the extension. It says 'Installation is not enabled". How to add / allow browser extension in this locust playwright and how to use webkit. Observed only the code for Chrome, Chromium and Firefox.

**Comment by cyberw** [comment]
Check playwright docs for more info. Never seen that error, and I dont think it is from ”our” code.
