### ISSUE TITLE
websocket  Can we use the websocket.websocektapp

### ISSUE THREAD

**Issue by luqy** [SvenskaSpel/locust-plugins#130]
![image](https://github.com/SvenskaSpel/locust-plugins/assets/42463694/cd34d5c6-3cec-4c33-babb-bafe2fad3bd6)

I tried to use the websocketapp method, but I found that this method seems unable to call send in task or send messages
I don't see it in the example either
I want to implement a socketIO implementation similar to that in JavaScript

**Comment by cyberw** [comment]
Sorry, I dont even know what a WebSocketApp is...
