### ISSUE TITLE
Custom webdriver options

### ISSUE THREAD

**Issue by Osmyslitelny** [SvenskaSpel/locust-plugins#137]
It would be amazing to have opportunity to override / change / add custom webdriver [options](https://github.com/SvenskaSpel/locust-plugins/blob/9c62e2996b5b50792c3688b53c6a271f6acee5fb/locust_plugins/users/webdriver.py#L22) for WebdriverClient / WebdriverUser

**Comment by cyberw** [comment]
Definitely. PR welcome. Could just be replacing the line that creates the Options to make it check first if a .options attribute exists on the class and use that instead if if does.

**Comment by TeerawatRksp** [comment]
hi, I try adjust some code of webdriverUser and client for overriding options on 
https://github.com/SvenskaSpel/locust-plugins/pull/191

This is my first contribution, hope it help the community.
