### ISSUE TITLE
Is there a desire for refactoring the Listener?

### ISSUE THREAD

**Issue by Midnighter** [SvenskaSpel/locust-plugins#14]
Inspired by your listeners, I have performed my own analysis. You can see all of the adapted code in https://github.com/Midnighter/starlette-delay/. I have put some effort into refactoring the listener and I think it's more flexible now and a bit cleaner in the sense of higher responsibility separation.

If you find these changes valuable, I can add tests and open a pull request. I'm also happy to change the license of my code to Apache 2.0 so it is compatible with this project.

**Comment by cyberw** [comment]
Hi! 

Thanks for your input! The current listener implementations could do with a refactoring.

Looking at your code right now it looks a bit over-engineered though (particularly the abstract base classes give me kind of a "Java written in Python" feeling :)

I think a more gentle refactoring of the current solution would be better (maybe just adding automatic registration of success/fail methods & some other cleanup)

**Comment by Midnighter** [comment]
The abstract classes are not strictly necessary that is true. They are a by-product of wanting different classes for handling the events that adhere to the same interface. So far I have implemented logging output and writing to a TimescaleDB which I think is valuable because other outputs can quickly be added or implemented by users themselves following the same design. So the abstract classes are only there to document the interfaces and create type annotations.

However, since you already have plans for a refactoring, I don't want to get in your way by pushing for a particular implementation.

**Comment by cyberw** [comment]
"plans" is a bit of an exaggeration :)

I dont mind abstract classes per se, its just that I dont think they add very much in this case. Most listeners should be this simple:

class Listener():
    def __init__(self, env):
        # hook up request_success/failure/quit/whatever event handlers defined in the subclass

class ExampleListener(Listener):
    def __init__(self, env):
        super().__init__(env)
        # do any initialization, like setting up db connection

    def request_success(self, request_type, name, response_time, response_length, exception, **_kwargs):
        # do the stuff

... so I think the abstract classes + loose coupling between listener/writer is not really needed.
