### ISSUE TITLE
Getting error when using distributed load generation along with timescale . 

### ISSUE THREAD

**Issue by dev-clumio** [SvenskaSpel/locust-plugins#141]
` Got DivisionByZero error when trying to update testrun, most likely because there were no requests logged`

I am trying to run locust in distributed mode along with that using `timescale` to put data into my tsdb .
I have created 3 ec2 instances for this purpose.
First one acts as master, while other two act as workers. 

On the master host I run: ` locust -f test.py --headless  --u 10 -t 10s --timescale --pghost=$PGHOST --pgport=5432 --pgpassword=$PASSWORD --pguser=$POSTGRES --master --expect-workers=2` 

On both worker nodes I run: `locust -f test.py  --worker --master-host=$MASTER_HOST`

When I do this, I get the error which I shared at the top. I checked my tsdb, there are no new enteries in `request` table, but `testrun` table has a new entry. 

But, when I run the test without distributed load generation using the command 
`locust -f test.py --headless  -u 10 -t 10s --timescale --pghost=$PGHOST --pgport=5432 --pgpassword=$PASSWORD --pguser=$POSTGRES` , I see new entries has been to `request` as well as `testrun` table. 

What could be going wrong here ? why am I not able to use distributed load generation along with timescale.

**Comment by cyberw** [comment]
You need to set `--timescale` on the worker as well I think?

**Comment by manefix** [comment]
that's weird but true, you need to set locust -f test.py  --worker --timescale --master-host=$MASTER_HOST

**Comment by wohui** [comment]
> that's weird but true, you need to set locust -f test.py --worker --timescale --master-host=$MASTER_HOST

got a error （locust: error: unrecognized arguments: --timescale）
when use --timescale  why？

**Comment by cyberw** [comment]
Is locust-plugins installed and is it locust latest version?

**Comment by wohui** [comment]
> Is locust-plugins installed and is it the latest version?

need installed by pip ？

**Comment by cyberw** [comment]
> need installed by pip ？

yes
