### ISSUE TITLE
Attribute Error: 'Timescale' object has no attribute '_run_id'

### ISSUE THREAD

**Issue by stevenj** [SvenskaSpel/locust-plugins#146]
Trying to use distributed workers, and I am getting:

```
load-test-worker-5    | [2023-09-19 02:13:44,258] eead9de91127/ERROR/root: Uncaught exception in event handler:
load-test-worker-5    | Traceback (most recent call last):
load-test-worker-5    |   File "/usr/local/lib/python3.11/site-packages/locust/event.py", line 40, in fire
load-test-worker-5    |     handler(**kwargs)
load-test-worker-5    |   File "/usr/local/lib/python3.11/site-packages/locust_plugins/listeners/timescale.py", line 240, in on_request
load-test-worker-5    |     "run_id": self._run_id,
load-test-worker-5    |               ^^^^^^^^^^^^
load-test-worker-5    | AttributeError: 'Timescale' object has no attribute '_run_id'
load-test-worker-5    |
load-test-worker-5    |
```
from all of them.

I have seen it happen on startup, but its always happens if I start the test with 1 user, and then re-start it with more (say 10).

**Comment by ikun-bug** [comment]
> 尝试使用分布式工作人员，我得到：
> 
> ```
> load-test-worker-5    | [2023-09-19 02:13:44,258] eead9de91127/ERROR/root: Uncaught exception in event handler:
> load-test-worker-5    | Traceback (most recent call last):
> load-test-worker-5    |   File "/usr/local/lib/python3.11/site-packages/locust/event.py", line 40, in fire
> load-test-worker-5    |     handler(**kwargs)
> load-test-worker-5    |   File "/usr/local/lib/python3.11/site-packages/locust_plugins/listeners/timescale.py", line 240, in on_request
> load-test-worker-5    |     "run_id": self._run_id,
> load-test-worker-5    |               ^^^^^^^^^^^^
> load-test-worker-5    | AttributeError: 'Timescale' object has no attribute '_run_id'
> load-test-worker-5    |
> load-test-worker-5    |
> ```
> 
> 来自他们所有人。
> 
> 我已经看到它在启动时发生，但如果我用 1 个用户开始测试，然后用更多用户（比如 10 个）重新启动它，它总是会发生。

How did you solve this problem
