### ISSUE TITLE
Issues with running Playwright scripts. 

### ISSUE THREAD

**Issue by mjohnson767** [SvenskaSpel/locust-plugins#150]
I'm hoping to use a locust/playwright implementation for load testing for applications that can't be used with protocol level tests and with applications requiring huge amounts of correlations. For browser-based testing the most successful has been the locust/selenium approach where we were able to run 175 concurrent workers on a single server. Playwright is a more solid tool and the codegen utility makes creating tests 10x faster. 

I've created a simple test with the export option of 'Python Async Library', included a required class method and attempted to run the test with 4 users. (using VSCode with the python and playwright extensions)
locust -f pyasyclib.py -u 4 -r 1 -t 120 --headless 
During playback it will either playback one user for one iteration or it'll playback 1 user for 3 iterations and then will freeze/stop in the terminal output. which plays back during the 120 second timeframe, not 4 concurrent users.
In running with the web interface:
locust -f pyasyclib.py -u 4 -r 1 -t 120 
The script runs without clicking 'Start swarming' for iteration and then stops. Clicking the Start swarming button does nothing and clicking stop does nothing as well. Required to do a ctrl-c in the terminal to cancel the paused test.
 
The graph from the run shows no metrics for Aggregated summary and the response time percentages. 

Performing a ctrl-c to stop the script shows the following Two errors:

The system cannot find the path specified.
The process tried to write to a nonexistent pipe.

// ***************************************************************************
PS C:\Users\{userID}\locustplaywright\locust-plugins\test> locust -f pyasyclib.py -u 4 -r 1 -t 120 --headless 
[2023-11-02 11:14:10,583] LHTU05CD943125T/INFO/locust.main: Run time limit set to 120 seconds
[2023-11-02 11:14:10,583] LHTU05CD943125T/INFO/locust.main: Starting Locust 2.18.0
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                         0     0(0.00%) |      0       0       0      0 |    0.00        0.00

[2023-11-02 11:14:10,593] LHTU05CD943125T/INFO/locust.runners: Ramping to 4 users at a rate of 1.00 per second
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Program Files\Python310\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\Lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\Lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Program Files\Python310\Lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Program Files\Python310\Lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
2023-11-02T17:18:31Z <Greenlet at 0x28ab2046160: <bound method ProactorEventLoop.run_forever of <ProactorEventLoop running=False closed=False debug=False>>> failed with KeyboardInterrupt    

The system cannot find the path specified.
[2023-11-02 11:18:31,997] LHTU05CD943125T/INFO/locust.main: Shutting down (exit code 0)
[2023-11-02 11:18:31,998] LHTU05CD943125T/INFO/locust.main: --run-time limit reached, shutting down
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                         0     0(0.00%) |      0       0       0      0 |    0.00        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------

The process tried to write to a nonexistent pipe.
// ***************************************************************************

I would really like to run some benchmarks with the tools and hoping this would be the right solution. I've ran benchmark tests with Artillery/Playwright and it can run with 10 users, anymore and the CPU is pegged. Right now I'm stuck with Trueclient that can only run 45 users per/server(slave). It would be great to get this working if you have some time. 

Here's the script:

import asyncio

from playwright.async_api import Playwright, async_playwright, expect
from locust_plugins.users.playwright import PlaywrightScriptUser

async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("https://www.saucedemo.com/")
    await page.wait_for_timeout(1000)
    await page.locator("[data-test=\"username\"]").click()
    await page.locator("[data-test=\"username\"]").fill("standard_user")
    await page.locator("[data-test=\"password\"]").click()
    await page.locator("[data-test=\"password\"]").fill("secret_sauce")
    await page.locator("[data-test=\"login-button\"]").click()
    await page.locator("[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    await page.locator("a").filter(has_text="1").click()
    await page.locator("[data-test=\"checkout\"]").click()
    await page.wait_for_timeout(1000)
    await page.locator("[data-test=\"firstName\"]").click()
    await page.locator("[data-test=\"firstName\"]").fill("test")
    await page.locator("[data-test=\"lastName\"]").click()
    await page.locator("[data-test=\"lastName\"]").fill("test")
    await page.locator("[data-test=\"lastName\"]").press("Tab")
    await page.locator("[data-test=\"postalCode\"]").fill("87556")
    await page.locator("[data-test=\"continue\"]").click()
    await page.locator("[data-test=\"finish\"]").click()
    await page.locator("[data-test=\"back-to-products\"]").click()
    await page.wait_for_timeout(1000)

    # ---------------------
    await context.close()
    await browser.close()

async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)

asyncio.run(main())

class ScriptBased(PlaywrightScriptUser):
    script = "pyasyclib.py"

**Comment by cyberw** [comment]
I havent used this in a while and it was always a little unstable under high load (using more than maybe >20 users/process). Looks like you’re using headless=False though? Thats one thing to change…

**Comment by cyberw** [comment]
And. Eh. You’re not supposed to run asyncio.run yourself? Try to get closer to the example code.
