### ISSUE TITLE
Add exemple about "extend the web UI to allow you to show custom data along side the built-in Locust stats"

### ISSUE THREAD

**Issue by obriat** [SvenskaSpel/locust-plugins#160]
The  [extending web ui page](https://docs.locust.io/en/stable/extending-locust.html#extending-web-ui) explains that it is possible to "extend the web UI" and points to [examples directory](https://github.com/locustio/locust/tree/master/examples), but i could not found a example that shows how to "show custom data along side the built-in Locust stats". Is it possible to add an example about that (or if I missed it add a direct link to the correct code) ?

I want to add hit-miss counter (based on Varnish ou  CDN headers values) for each request, I managed to display it on a custom route (thanks to [events.py](https://github.com/locustio/locust/blob/master/examples/events.py)) but it would be great if I could add these **as a additional column on the main page**. And it will be even greater to be available in vary data export mode.

**Comment by cyberw** [comment]
Hi! Does this really relate to `locust-plugins`? File a new ticket in the "core" locust project instead if not, and maybe ping andrewbaldwin44 (as he's the UI expert :)

**Comment by obriat** [comment]
Sorry, you're right, I mixed my browser tabs and post to the wrong repo :( 
Anyway thanks for the tip
