### ISSUE TITLE
Can the postgres field testplan be customized from a locustfile during run-time?

### ISSUE THREAD

**Issue by pranavthombare** [SvenskaSpel/locust-plugins#161]
https://github.com/SvenskaSpel/locust-plugins/issues/159

As asked in this issue, I want to update the override-test-plan field from a locustfile. Is there a way that I can set that field in my locustfile during the runtime. 

Assuming that I run a locust UI and give a field where user can enter the testplan name and it reflects on the grafana page.

**Comment by cyberw** [comment]
right now it cant be done in locust, because it doesnt show custom arguments under argument groups. I'll see if it can be fixed.

You can do it from code, like this:

`os.environ["LOCUST_OVERRIDE_PLAN_NAME"] = "my_special_name"`

**Comment by pranavthombare** [comment]
I tried using the above method. But I wasn't able to make the above change show any effect. 

I'm trying it on a locust UI where I keep running different load tests. I want to rename each load test differently. If I can change that in the UI when starting a new test, that would solve my issue. 

Until then my best guess is that i'm using `os.environ["LOCUST_OVERRIDE_PLAN_NAME"] = "my_special_name"` in a wrong location. Maybe in HTTPUser class?
