### ISSUE TITLE
AMQP support

### ISSUE THREAD

**Issue by NoodleGameDev** [SvenskaSpel/locust-plugins#164]
**TL;DR: title, I have an AMQPUser class which I'd love to contribute!**

Hey there!
I work as a junior software dev in an enterprise where we needed AMQP support to load test our system, so I made an AMQPUser class which is fully functional, including the firing all events needed to make it tick. I really liked Locust as a project, and I want to send my AMQPUser as my first open source contribution.  Feels like a right of passage to the profession.

Contact me 👍

**Comment by cyberw** [comment]
Awesome :) Make a PR to locust-plugins and I’ll have a look 👍👍
