### ISSUE TITLE
404 in docs

### ISSUE THREAD

**Issue by MalteMagnussen** [SvenskaSpel/locust-plugins#165]
When I click the "If you want to [send reporting data to that database & graphing system you like](https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/listeners.py)," link, I get a 404.

Under "Hackable": https://docs.locust.io/en/stable/what-is-locust.html#features

![image](https://github.com/SvenskaSpel/locust-plugins/assets/11192971/b4f42476-a01d-413b-9a60-fcf4d1180162)

![image](https://github.com/SvenskaSpel/locust-plugins/assets/11192971/a0434a97-9673-41a8-81fe-2f7548e3e76c)

**Comment by cyberw** [comment]
Thanks for reporting! Correct link is https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/listeners/timescale.py

**Comment by cyberw** [comment]
Actually, https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/dashboards is more useful.
