### ISSUE TITLE
not able to launch browser with playwright example

### ISSUE THREAD

**Issue by vbpatel73** [SvenskaSpel/locust-plugins#166]
I tried to run locust with playwright example with recording script but browsers not launched and do not see anything in log.Can someone give me detailed steps how to set up pls?

**Comment by cyberw** [comment]
what happens when you try to run one of the examples?

**Comment by vbpatel73** [comment]
![image](https://github.com/SvenskaSpel/locust-plugins/assets/46678361/2b9ece03-b136-4b40-b1e9-6df9b6b9d32a)

**Comment by vbpatel73** [comment]
this is what I am getting when set up this project and run locust -f examples/playwright_ex.py with 1 user and 5 seconds to ramp

**Comment by vbpatel73** [comment]
let me know if i am doing something wrong pls

**Comment by vbpatel73** [comment]
[2024-02-20 18:05:38,907] Vikash/WARNING/locust.main: Python 3.8 support is deprecated and will be removed soon
[2024-02-20 18:05:38,911] Vikash/INFO/locust.main: Starting web interface at http://localhost:8089 (accepting connections from all network interfaces)
[2024-02-20 18:05:38,938] Vikash/INFO/locust.main: Starting Locust 2.23.1
[2024-02-20 18:06:04,799] Vikash/INFO/locust.runners: Ramping to 1 users at a rate of 5.00 per second

**Comment by cyberw** [comment]
I think the page just never finishes loading. Use a non-headless browser to see what is going on. This is the default when running using run_single_user (just run the example using `python playwright_ex.py`), but you can also set it manually, I dont remember exactly but I think you can just set a property on the user class.

**Comment by vbpatel73** [comment]
@cyberw I can see browser set up headless as below:
![image](https://github.com/SvenskaSpel/locust-plugins/assets/46678361/0440fddd-076e-4395-95f0-0ca0ea61c332)

**Comment by vbpatel73** [comment]
nothing happened when i ran with python command
![image](https://github.com/SvenskaSpel/locust-plugins/assets/46678361/d58e53d9-6567-4a6c-9ffe-eec1b13634f6)

**Comment by cyberw** [comment]
Well, if you're trying to launch a recording, you can also run it directly, and see what happens then. 

`python examples/playwright-recording.py`

If that doesnt tell you anything, try running it in the debugger and confirming exactly where in the python code it gets stuck.

**Comment by vbpatel73** [comment]
I tried playwright-recording.py directly and it works

**Comment by vbpatel73** [comment]
when I debug i am getting this 
![image](https://github.com/SvenskaSpel/locust-plugins/assets/46678361/cfa47f70-0782-46e7-9155-d1e6340ad477)

**Comment by cyberw** [comment]
oooh... you are on windows :)

The SystemExit exception is just locust exiting, you should read the line before it. If you're hitting that code then playwright could not be imported (is not properly installed). but I dont know how you could that error when debugging, and not when running the locustfile from command line... If I have time I'll have a go at launching this on my windows machine...

**Comment by cyberw** [comment]
The problem was one of the flags used when starting chromium (--no-sandbox), it just hangs on windows.

I think it causes a *small* performance hit on other OS:es but all of this is kind of experimental anyway, so I disabled it.

Try installing the new release (4.4.1)

**Comment by vbpatel73** [comment]
now with new code, i am getting this 
![image](https://github.com/SvenskaSpel/locust-plugins/assets/46678361/c38f9ed7-19e5-42c2-8df1-3226c4e217d2)

**Comment by vbpatel73** [comment]
No error now but debug also not showing anything wrong

**Comment by cyberw** [comment]
I wonder what that thing about "proactor" is about, I dont think I got that message myself. 

The things I fixed only really apply to "regular" locust users, not script based ones (the scripted ones shouldnt have that particular issue, but maybe they have others). Can you run a regular one?

You might wanna update your python version as well. Sorry, thats all the time I have for now.

**Comment by vbpatel73** [comment]
what do you mean by regular one pls? I updated python. one more question can I run it from WSL on windows?

**Comment by cyberw** [comment]
By regular I meant PlaywrightUser (as opposed to PlaywrightScriptUser). I've never tried this in WSL, no idea if it will work but my guess is that it would _not_ work. I didnt even know running GUI apps (like a browser) in WSL was supported :)

**Comment by vbpatel73** [comment]
I tried remving playwrightScriptuser class and keep only Playwrightuser class and run script but still same result. Now if i try to run on macOs will it work?

**Comment by KevinEvansSrAeries** [comment]
Having same issue. using windows. added 4.4.2 via pip install --upgrade  locust-plugins[playwright]
