### ISSUE TITLE
Does locust support thick-client application?

### ISSUE THREAD

**Issue by NaliniSake** [SvenskaSpel/locust-plugins#176]
I'm trying to start the Excel.exe file with simple python OS operation, below is the code. The Locust starts the file with no issues but do not see any Transaction details(KPIs) in Locust web user interface. How can I capture the  KPI/Metrics details in Locust web UI (http://localhost:8089 ). Please help me with request.

class SampleTest(User):
    @task
    def launch(self):
        os.startfile("C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE")
        wait_time = constant(2)

**Comment by NaliniSake** [comment]
Could someone please help me with my request?

**Comment by cyberw** [comment]
Hi! No, locust does not really support thick-client applications. If your exe/process does finish running after on its own (with no need for interaction) you could create a custom user for processes https://docs.locust.io/en/stable/testing-other-systems.html

But it's an odd use case even then. Locust is made for load testing server applications.
