### ISSUE TITLE
Add Yandex-Tank visualization

### ISSUE THREAD

**Issue by santAndras** [SvenskaSpel/locust-plugins#177]
I would like to implement a locust-plugin where you could run Locust CLI but with Yandex-Tank visualization.

Example Yandex-Tank CLI:
![yandex-tank-console](https://github.com/SvenskaSpel/locust-plugins/assets/110020063/88daeb47-1248-4516-b1c9-9a7c295528e6)

**Comment by santAndras** [comment]
I'm going to close it because I wanted to create this issue with another account.

**Comment by cyberw** [comment]
PR:s welcome!
