### ISSUE TITLE
Run Locust with Yandex Tank visualization

### ISSUE THREAD

**Issue by asaanta** [SvenskaSpel/locust-plugins#178]
I would like to implement a plugin to be able to run Locust in headless mode with Yandex Tank visualization.

Example Yandex Tank visualization:
![image](https://github.com/SvenskaSpel/locust-plugins/assets/80908967/39441abf-0a70-4953-9403-28f1574ecbf5)

**Comment by cyberw** [comment]
@asaanta this would be very welcome!

**Comment by asaanta** [comment]
Hey @cyberw, I'm on it! I've been busy with other stuff, but I'm close to completing it.

**Comment by cyberw** [comment]
Cool! If you do make it work, maybe we could even take it into locust core.
