### ISSUE TITLE
playwright plugin does not return data to the locust frontend

### ISSUE THREAD

**Issue by KevinEvansSrAeries** [SvenskaSpel/locust-plugins#179]
please clarify the cli command to make the locustplaywrightpluging work. I copied you example but get no data in the locust headful browser. 
python playwright_ex.py
Locust -f playwright_ex.py
...
Note: I am seeing data when I test various apis but not getting date with playwright / UI tests

**Comment by cyberw** [comment]
Often it is waiting for elements to load, try loading a different page or something. Sorry, I'm unable to offer support for this, I think you'll have to debug it yourself.

**Comment by KevinEvansSrAeries** [comment]
Works python direct, headless=True. 
Should I be able to see data based on UI/Playwright in the Locust front end. Just making sure I'm not looking for something that does not exist. I've tried my own URL and the provided example with the same result (no data/appears to be frozen.

**Comment by cyberw** [comment]
Nono, it should work. What happens in the browser? Try with headless=True or the locustfile directly using run_single_user()

**Comment by KevinEvansSrAeries** [comment]
Using run_single_user, calling a codegen generated async python script, the process stops here:
![image](https://github.com/SvenskaSpel/locust-plugins/assets/87541430/437150a4-8067-4d15-bac3-7f602832cc11)

**Comment by KevinEvansSrAeries** [comment]
@cyberw I upgraded everything to the latest version (python 3.11.1 to 3.12.2, locust, playwright, etc, ...
Unfortunately, same stop/hang
![image](https://github.com/SvenskaSpel/locust-plugins/assets/87541430/ed7edba0-7d67-42fd-88a3-1ea61e478d0c)

**Comment by KevinEvansSrAeries** [comment]
everything has stopped now! APIs are doing the same thing

**Comment by cyberw** [comment]
Ah, I didnt see that you were on windows. You might want to try removing some of the command line options for chromium (in users/playwright.py)

**Comment by KevinEvansSrAeries** [comment]
Please explain: My CLI command has no options other than -f 
![image](https://github.com/SvenskaSpel/locust-plugins/assets/87541430/df825869-d5af-474a-95f6-94a4279b585c)

**Comment by KevinEvansSrAeries** [comment]
I've got it running and reporting statitics without the plugin but I'm sure the plugin would make my life much easier and would really like to resolve any challenges I'm encountering. I'm Load testing using Locust, Playwright and API endpoints. Can you add an example of this to your list? Main challenge doing asynchronous Playwright load tests

**Comment by cyberw** [comment]
I meant the arguments in playwright.py, here https://github.com/SvenskaSpel/locust-plugins/blob/507ff46808d2945f2eea6ed46aa2d69117159ede/locust_plugins/users/playwright.py#L296

Anyways, when I see where the debugger stops, it is actually more likely that there is just some element on your page that never loads. Try passing wait_until='commit' (see https://playwright.dev/python/docs/api/class-page#page-goto-option-wait-until) and then explicitly waiting for some element to become visible.

**Comment by KevinEvansSrAeries** [comment]
@cyberw Following your threads on locust-playwright gevent-asyncio, 
Does this appear correct?
@task(1)
    def locust_loadClassic(self):
        with self.client.get(
            "", catch_response=True, name="UI - Load Classic"
        ) as response:
            print("Running: UI - Load Classic")
            while True:  # and not other_exit_condition
                future = asyncio.run_coroutine_threadsafe(inner_loadClassic(self), loop)
                while not future.done():
                    gevent.sleep(1)
                loop.run_until_complete(future)

**Comment by cyberw** [comment]
Uhm. Maybe? In my approach 

You’re I have only one loop. Maybe your approach could work as well. Use the test_start and test_stop event handlers to stop/start the event loop and the sync-decorator to make an async function syncronous.

Tbh, I think we should write an async worker implementation (one that doesnt use gevent). But that would be a significant amount of work…

**Comment by BuduruNarasimhulu** [comment]
currently working on load testing with Locust and Playwright for automation scenarios. I’ve been using the Locust plugin, and as shown in the image I shared, the dashboard is only displaying failure stats, even though my Playwright script runs smoothly on its own. The issue only seems to occur during load testing. Do you have any suggestions or tips on what might be causing this, or how I could improve the integration of Locust with Playwright for UI testing?
locust_script.py:<img width="596" alt="Screenshot 2024-12-14 at 1 36 01 AM" src="https://github.com/user-attachments/assets/4d1bc79d-4f8d-43ff-9457-8b9e5adc08a9" />
