### ISSUE TITLE
[MQTT] locust-plugins is incompatible with paho-mqtt >= 2

### ISSUE THREAD

**Issue by flbraun** [SvenskaSpel/locust-plugins#180]
After a long time of inactivity the Paho team has released a new major version for the Paho MQTT Python library ([release notes](https://github.com/eclipse/paho.mqtt.python/releases/tag/v2.0.0), [migration guide](https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html)).  
This major release changes the expected signature of callbacks (e.g. `on_connect`) which breaks locust-plugin's `MqttUser`.

I see three options to proceed:
1. Pin `paho-mqtt` to `>=1.5.0,<2` .
2. Patch `MqttUser` to use the original - but now deprecated - callback signature.
3. Adapt callback signatures in `MqttUser` to use the new style. This may lead to breaking changes if users customized `MqttUser`.

Personally, I prefer option 3. The new release of Paho brought a lot of under-the-hood-improvements the Locust ecosystem would benefit from in the long run.
I'm willing to provide a PR once we agreed on a solution.

**Comment by cyberw** [comment]
Option 3 sounds best, PR welcome!

**Comment by emgarten** [comment]
A workaround for this is to copy the mqtt user to your own code base, then add the following line per the migration guide referenced above.

`callback_api_version=mqtt.CallbackAPIVersion.VERSION1`

All code stays the same but it will now work with Paho 2.0.0

**Comment by flbraun** [comment]
Sorry for my inactivity on the topic, I was very busy.

In the meantime, the Paho team has released version [2.1.0](https://github.com/eclipse/paho.mqtt.python/releases/tag/v2.1.0) which changes the default callback api version from 2 back to 1 due to backlash.
Since this is the new default I think we should pin Paho to `>=2.1.0`. This way users of locust-plugins can still benefit from the 2.x improvements _and_ we don't have to introduce a breaking change for users who customized `MqttUser`.

**Comment by flbraun** [comment]
@cyberw Thanks for merging the PR. Could we get a new release, please? I'd consider the issue done after that.
