### ISSUE TITLE
Gret the "Number of user" defined in the web gui

### ISSUE THREAD

**Issue by zinig** [SvenskaSpel/locust-plugins#181]
I'm traing to get the number of user defined in the web gui but environment.parsed_options.num_users is always set to 0.

i have not find a way to gete the number of users and the ramp up.

I can't use locust

**Comment by cyberw** [comment]
Your ticket is not in the right repo :)

You could try the latest version (pip install --pre -U locust), something related was fixed in https://github.com/locustio/locust/pull/2656/commits/b2e7f12d1c10b7e59dda97e3a727d0936aecc79c
