### ISSUE TITLE
question: add a target environment discriminator column in timescale and edit the grafana charts to allow target environment selection

### ISSUE THREAD

**Issue by ionutab** [SvenskaSpel/locust-plugins#182]
Hello,
I'm creating this issue since I have an idea and I want to know if it is good or not.
Sorry, it is most likely in the wrong place but I don't know where to ask.

I want to work on extending the current timescale implementation.
It would add a "target environment name" configuration and would save that on a column in some db tables as well.
At the same time a "target environment" filter would allow Grafana users to view only data from the test runs targeting a specific environment.
To keep things backwards compatible, the default would be "default" or "None" or something like that.

The question is:
Is this a good idea that would fit into the overall direction of the locust-plugins?

Thanks!

**Comment by ionutab** [comment]
Nevermind, I just saw the `env` filter in the Locust Testruns grafana dashboard.
I just need to understand what parameter I need to pass in order to the `env` field to be populated in the `testrun` database table.
I'll solve it sooner or later.
Sorry and thank you!

**Comment by ionutab** [comment]
Hmmm, sorry.
I just realized that the `--test-env` / `LOCUST_TEST_ENV` configuration is not documented at https://docs.locust.io/en/stable/configuration.html.
Is it going to be deprecated?

**Comment by cyberw** [comment]
--test-env is specific to locust-plugins (so no, its not deprecated :)

**Comment by ionutab** [comment]
Ah yes, I see, you're right.
Thank you!
