### ISSUE TITLE
Additional rps calculation rules

### ISSUE THREAD

**Issue by waitingSunset** [SvenskaSpel/locust-plugins#183]
I find the constant_total_ips method of wait_time.py very useful, 
and I have a special idea to define a TPS concept. 
For example, if @task_a, @task_b, and @task_c exist in a TaskSet, and I set the TPS parameter to 10, the request rate of each task should be 10, not the total number of requests for each task should be 10
I wonder if the suggestion is reasonable

**Comment by cyberw** [comment]
Hi! That sounds useful, and should be possible. If you implement it I'll have a look!
