### ISSUE TITLE
Empty statistic and a chart data with limited iterations

### ISSUE THREAD

**Issue by Neonchen** [SvenskaSpel/locust-plugins#185]
Using Locust 2.29.1 with limited Iterations (e.g. 10) shows no statistic and no chart data in the web ui. But when I download the report all data are available. Is this a bug?

**Comment by cyberw** [comment]
hi! is this issue related to locust-plugins or did you mean to file it in the locust repo? 

It does sound like a bug, but can you create a ticket there instead and add instructions & locustfile for how to reproduce it?
