### ISSUE TITLE
Dashboard plugin - Support for app namespacing and metadata

### ISSUE THREAD

**Issue by csuriano23** [SvenskaSpel/locust-plugins#189]
Hello there,
is there currently support in grafana+timescale dashboard plugin for any of the following?

- Namespacing the dashboard per application, so that different applications can be tracked in different dashboards
- putting a tag / label for an application, so that somewhere in the graphs we can distinguish which tag was active during a certain timeframe

**Comment by cyberw** [comment]
Hi! Dashboards only supports ”namespacing” by test plan (locustfile) file name. For more advanced reporting there is https://locust.cloud, but that is a hosted/paid solution.
