### ISSUE TITLE
install error~

### ISSUE THREAD

**Issue by hdzys** [SvenskaSpel/locust-plugins#19]
Installing collected packages: confluent-kafka, locust, locust-plugins
    Running setup.py install for confluent-kafka ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-1jhg23va\\confluent-kafka\\setup.py'"'"'; __file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-1jhg23va\\confluent-kafka\\setup.py'"'"';f=getattr(tokeniz
e, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-jnpwxu7z\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python\Inc
lude\confluent-kafka'
         cwd: C:\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va\confluent-kafka\
    Complete output (51 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\confluent_kafka
    copying confluent_kafka\deserializing_consumer.py -> build\lib.win-amd64-3.8\confluent_kafka
    copying confluent_kafka\error.py -> build\lib.win-amd64-3.8\confluent_kafka
    copying confluent_kafka\serializing_producer.py -> build\lib.win-amd64-3.8\confluent_kafka
    copying confluent_kafka\__init__.py -> build\lib.win-amd64-3.8\confluent_kafka
    creating build\lib.win-amd64-3.8\confluent_kafka\admin
    copying confluent_kafka\admin\__init__.py -> build\lib.win-amd64-3.8\confluent_kafka\admin
    creating build\lib.win-amd64-3.8\confluent_kafka\avro
    copying confluent_kafka\avro\cached_schema_registry_client.py -> build\lib.win-amd64-3.8\confluent_kafka\avro
    copying confluent_kafka\avro\error.py -> build\lib.win-amd64-3.8\confluent_kafka\avro
    copying confluent_kafka\avro\load.py -> build\lib.win-amd64-3.8\confluent_kafka\avro
    copying confluent_kafka\avro\__init__.py -> build\lib.win-amd64-3.8\confluent_kafka\avro
    creating build\lib.win-amd64-3.8\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\verifiable_client.py -> build\lib.win-amd64-3.8\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\verifiable_consumer.py -> build\lib.win-amd64-3.8\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\verifiable_producer.py -> build\lib.win-amd64-3.8\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\__init__.py -> build\lib.win-amd64-3.8\confluent_kafka\kafkatest
    creating build\lib.win-amd64-3.8\confluent_kafka\schema_registry
    copying confluent_kafka\schema_registry\avro.py -> build\lib.win-amd64-3.8\confluent_kafka\schema_registry
    copying confluent_kafka\schema_registry\error.py -> build\lib.win-amd64-3.8\confluent_kafka\schema_registry
    copying confluent_kafka\schema_registry\json_schema.py -> build\lib.win-amd64-3.8\confluent_kafka\schema_registry
    copying confluent_kafka\schema_registry\protobuf.py -> build\lib.win-amd64-3.8\confluent_kafka\schema_registry
    copying confluent_kafka\schema_registry\schema_registry_client.py -> build\lib.win-amd64-3.8\confluent_kafka\schema_registry
    copying confluent_kafka\schema_registry\__init__.py -> build\lib.win-amd64-3.8\confluent_kafka\schema_registry
    creating build\lib.win-amd64-3.8\confluent_kafka\serialization
    copying confluent_kafka\serialization\__init__.py -> build\lib.win-amd64-3.8\confluent_kafka\serialization
    creating build\lib.win-amd64-3.8\confluent_kafka\avro\serializer
    copying confluent_kafka\avro\serializer\message_serializer.py -> build\lib.win-amd64-3.8\confluent_kafka\avro\serializer
    copying confluent_kafka\avro\serializer\__init__.py -> build\lib.win-amd64-3.8\confluent_kafka\avro\serializer
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\Users
    creating build\temp.win-amd64-3.8\Release\Users\DELL
    creating build\temp.win-amd64-3.8\Release\Users\DELL\AppData
    creating build\temp.win-amd64-3.8\Release\Users\DELL\AppData\Local
    creating build\temp.win-amd64-3.8\Release\Users\DELL\AppData\Local\Temp
    creating build\temp.win-amd64-3.8\Release\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va
    creating build\temp.win-amd64-3.8\Release\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va\confluent-kafka
    creating build\temp.win-amd64-3.8\Release\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va\confluent-kafka\confluent_kafka
    creating build\temp.win-amd64-3.8\Release\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va\confluent-kafka\confluent_kafka\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\python\include -Id:\python\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IC:\Program F
iles (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\1
0.0.18362.0\cppwinrt" /TcC:\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va\confluent-kafka\confluent_kafka\src\confluent_kafka.c /Fobuild\temp.win-amd64-3.8\Release\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va\confluent-kafka\confluent_kafka\src\confluent_kafka.obj
    confluent_kafka.c
    C:\Users\DELL\AppData\Local\Temp\pip-install-1jhg23va\confluent-kafka\confluent_kafka\src\confluent_kafka.h(22): fatal error C1083: 无法打开包括文件: “librdkafka/rdkafka.h”: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-1jhg23va\\confluent-kafka\\setup.py'"'"'; __file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-1jhg23va\\confluent-kafka
\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-jnpwxu7z\install-record.txt' --single-version-externally-managed --compile
 --install-headers 'd:\python\Include\confluent-kafka' Check the logs for full command output.

**Comment by cyberw** [comment]
Hi! Looks like it is related to confluent-kafka rather than locust-plugins specifically.. maybe check stackoverflow?

**Comment by yuzugullu** [comment]
I got a similar error, It seems that when doing it on Windows it requires a bunch of dependencies like kafka, postgresql, c++ build tools, etc. Not sure why

**Comment by cyberw** [comment]
You could try installing again, passing `--no-deps` to pip. The stuff relying on kafka etc wont work of course, but maybe your’re not interested in that.
