### ISSUE TITLE
AssertionError: assert m is not none

### ISSUE THREAD

**Issue by tyler-suard-parker** [SvenskaSpel/locust-plugins#193]
locustfile.py", line 15, in my_task
    self.send(
Lib\site-packages\locust_plugins\users\socketio.py", line 98, in send
    assert m is not None
           ^^^^^^^^^^^^^
AssertionError

It seems the issue is in this line of code here:

m = re.search(r'(\d*)\["([a-z]*)"', body)

I already have a format that I need to follow for the websocket server I am testing.  Why are you enforcing a different format?

**Comment by cyberw** [comment]
I built this for a very specific use case a long time ago. Feel free to override this function (or even suggeste a better implementation in a PR). I'm not using it atm.
