### ISSUE TITLE
Unable to run playwright plugin with locust

### ISSUE THREAD

**Issue by kirankumar-grootan** [SvenskaSpel/locust-plugins#197]
when i run playwright -f locustfile.py it shows

ERROR:root:'playwright' is not installed by default; you need to install it using "pip install 'locust-plugins[playwright]'"

```python
from locust_plugins.users.playwright import PlaywrightScriptUser

class ScriptBased(PlaywrightScriptUser):
  script = "playwright.py"
```

I have packages installed
locust-plugins
locust 2.32.0 from /usr/local/lib/python3.11/site-packages/locust (Python 3.11.10)
locust-plugins[playwright]
playwright 1.48.0

**Comment by kirankumar-grootan** [comment]
multiple files are getting executed in the back. which is causing the issue

**Comment by ericdrosas87** [comment]
Can you say more about the resolution @kirankumar-grootan ? I'm currently experiencing this same issue
