### ISSUE TITLE
When I use the docker to run master and slave,the result can't write into the requests table

### ISSUE THREAD

**Issue by FANHIDE** [SvenskaSpel/locust-plugins#2]
When I use the docker to run master and slave type ,the result can't write into the requests table:
so my question is:
does the locust-plugin TimescaleListener support the slave type. And what about this code means:
![image](https://user-images.githubusercontent.com/29531967/75411447-389d8f00-595a-11ea-8c87-6ff676aa88fd.png)

**Comment by cyberw** [comment]
Hi! Yes, the TimescaleListener supports slave type runs, but I've only use it together with locust-swarm (https://github.com/SvenskaSpel/locust-swarm) which sets the LOCUST_RUN_ID env var. I'll adjust that line of code to make it optional.

**Comment by cyberw** [comment]
try now, I have released it as 0.0.42. you'll need to add a "pid" (integer) field to the request table as well (unrelated to this change)

**Comment by cyberw** [comment]
(see https://github.com/SvenskaSpel/locust-plugins/commit/c3cac416d75466e899b69416915509c0e1f8d08d)

**Comment by FANHIDE** [comment]
ok , i will try
