### ISSUE TITLE
Suggestion: break up the plugins by functionality

### ISSUE THREAD

**Issue by joaonc** [SvenskaSpel/locust-plugins#22]
I was looking to add the `--iterations` functionality to my tests and the implementation here works well.   However, installing `locust-plugins` also installs a bunch of dependencies (as specified in `setup.py`) and my company is stringent with bringing in new packages that we don't need (rightfully so, IMO).

Would be nice to be able to add just that functionality..

What I ended up doing was copying most of `__init__.py` into my project with just what I needed, but I would much rather install a package with just that functionality.

Same for the other plugins.

* `locust-iterations`
* `locust-mongo-reader`
* etc.

Granted, this would cause for very small projects, which would likely make them harder to maintain, but would avoid the dependency overload.

**Comment by joaonc** [comment]
PS: What I'm suggesting is also how pytest does it.  Small and specialized plugins.

Now that I think of it, maybe Locust could benefit from something like pytest, where it calls functions (hooks) if they exist in a certain file (conftest.py) or the plugin registered itself on instalation.  In other words, makes adding functionality very easy.  Would this be a good suggestion for Locust?

Pytest certainly benefited from having people contribute via plugins and Locust would too.

**Comment by cyberw** [comment]
I think this makes sense. I experiemented with this a while back (using extras https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

If you build it and it looks good then I can merge, but you probably have to do it yourself :)

**Comment by joaonc** [comment]
That link seems to be outdated. I think this is the new one (pls correct if wrong):
https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies

What do you think about [pluggy](https://github.com/pytest-dev/pluggy)?   Would this be harder to implement or goes agains Locust guidelines on bringing a new dependency, making it a non-starter?

**Comment by cyberw** [comment]
How does pluggy relate to package dependencies?

**Comment by joaonc** [comment]
`pluggy` is a new package that would need to be installed when you `pip install locust`.  That's what I meant with _"bringing in a new dependency"_.

I guess the question here is whether or not the locust team wishes to provide more support for extensibility, at which point adding one more package (`pluggy`) in [setup.py](https://github.com/locustio/locust/blob/master/setup.py) would be justified.

My original suggestion was to break up `locust-plugins` into multiple, smaller, specialized plugins.  If locust supports pluggy, then breaking up `locust-plugins` would be done one way.   If not, then might be harder to separate `locust-plugins`.

Do you think the locust team (which you are part) is open to adding support to having locust become more easily extensible with the use of `pluggy`?  (or maybe some other way).
