### ISSUE TITLE
Use action='store_true' for transaction manager '--log_transactions_in_file'

### ISSUE THREAD

**Issue by ctstone** [SvenskaSpel/locust-plugins#26]
When using a boolean argument value, it's more intuitive to let the flag itself assign a `True` value using the `action` attribute. 

Here's an example from the locust argparser:

```python
stats_group.add_argument(
    "--print-stats",
    action="store_true",
    help="Print stats in the console",
    env_var="LOCUST_PRINT_STATS",
)
```

Since this would be a breaking change, it might be a good opportunity to deprecate this flag and switch it to `log-transactions-in-file` for consistency with the other locust options that use dashes instead of underscores.

**Comment by cyberw** [comment]
This is for locust core, right?

**Comment by ctstone** [comment]
No, this is for the `--log_transactions_in_file` flag which is part of locust-plugins TransactionManager. The example above is from core to show `store_true` functionality.

At first glance I was running `locust --log_transactions_in_file MyUser` which has the effect of swallowing up the user argument. Since it's a boolean flag we can use `store_true` and the value will be inferred by its presence or absence.

I've attached a PR if you would like to consider the change.

**Comment by cyberw** [comment]
Ah, I misunderstood your example.
