### ISSUE TITLE
CSV output does not encode strings with commas, quotes, etc.

### ISSUE THREAD

**Issue by ctstone** [SvenskaSpel/locust-plugins#30]
TransactionManager is capable of writing arbitrary strings to its CSV output, but it does not currently handle special special characters like `,` and `"`.

I suggest using the built-in [csv](https://docs.python.org/3/library/csv.html) module, which is how Locust core [handles encoding](https://github.com/locustio/locust/blob/master/locust/stats.py#L890).

**Comment by cyberw** [comment]
PRs welcome
