### ISSUE TITLE
Question regarding the Timescale listener plugin

### ISSUE THREAD

**Issue by Treshch1** [SvenskaSpel/locust-plugins#31]
https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/timescale_listener_ex.py
> 2. Set up the table: executing timescale_schema.sql

What do you mean by this row? Where should I get info on what data would be received from the locust?
Can you send me an example of the correct table configuration for this listener?

**Comment by cyberw** [comment]
Sorry, guess I should link it or something. It is moderately visible if you clone the repo, but completely impossible to know if you just installed the package :)

https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/timescale_schema.sql

**Comment by Treshch1** [comment]
Thanks for the help!!!

**Comment by Treshch1** [comment]
@cyberw could you also please help me with pointing what exactly should contain these two env vars PGHOST and PGPORT? I'm not sure that host and port would be enough to get the connection since I should point somewhere the name of the database?

Should it be something like ... ?
> export PGHOST=postgres:qqweqqwe@127.0.0.1:5432/postgres

**Comment by Treshch1** [comment]
@cyberw don't you know why grafana requires to add graphite data source to add and use your dashboard there? Shuold I just create empty data source?

**Comment by cyberw** [comment]
It does not require graphite, probably it is only there by accident. yes an empty datasource should be fine.

**Comment by Treshch1** [comment]
As you see ...
![image](https://user-images.githubusercontent.com/30592600/102018557-a2b2e380-3d76-11eb-95c3-e7d5d8171a87.png)

**Comment by cyberw** [comment]
Yes, what I meant is that it doesnt actually *use* graphite. It is just there by accident for some reason. I can fix it...

**Comment by cyberw** [comment]
new version uploaded now!

**Comment by Treshch1** [comment]
@cyberw 
I hope that it is the last issue I faced during listener integration. Do have any ideas how I can fix it? The hint has been checked in the docker container `postgresql.conf` file and the docker container has been restarted. Maybe you faced with this issue too and believe that you have the answer 🙈
![image](https://user-images.githubusercontent.com/30592600/102020849-8e75e300-3d84-11eb-88e3-76403eda4f46.png)

**Comment by Treshch1** [comment]
After several hours of struggling, found the discussion here and it helped.  
https://github.com/SvenskaSpel/locust-plugins/issues/11

Would be good to add this issue directly to the file in the comments https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/timescale_listener_ex.py

**Comment by cyberw** [comment]
👍  I have added a link to the docs. Timescale setup is way harder than it should be...
