### ISSUE TITLE
CSVDictReader bug

### ISSUE THREAD

**Issue by fumuumuf** [SvenskaSpel/locust-plugins#34]
In CSVDictReader, the first line is considered as data after the second round.

https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/csvreader.py#L40

I suggest the following modification.

```
# reuse file on EOF
self.file.seek(0, 0)
self.reader = csv.DictReader(self.file) # add
return next(self.reader)
```

**Comment by cyberw** [comment]
Sounds good! Can you make a PR?

**Comment by shuang790228** [comment]
> > Hello, is it possible to specify a delimiter other than ',' ? We'd like to handle some .tsv files.
> 
> Hi! It should be fairly easy to modify CSV/CSVDictReader to pass on arguments (using *args and **kwargs) to the underlying csv implementation. Dont have time to do it myself but a PR would be welcome.

yeah, thanks for the confirmation!
