### ISSUE TITLE
Websocket test issues

### ISSUE THREAD

**Issue by j2l** [SvenskaSpel/locust-plugins#35]
Trying to use the websocket-socket.io [plugin](https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/users/socketio.py) and got the error `No User class found!`

My code:
```
import json
import logging
import re
import time
import gevent
import websocket
from locust import HttpUser


class SocketIOUser(HttpUser):
    abstract = True

    def __init__(self, parent):
        super().__init__(parent)
        ws_host = re.sub(r"https://REDACTED.com", "", self.host)
        self.ws = websocket.create_connection(f"wss://{ws_host}")
        gevent.spawn(self.receive)

    def receive(self):
        message_regex = re.compile(r"(\d*)(.*)")
        description_regex = re.compile(r"<([0-9]+)>$")
        response_time = None
        while True:
            message = self.ws.recv()
            logging.debug(f"WSR: {message}")
            m = message_regex.match(message)
            if m is None:
                # uh oh...
                raise Exception(f"got no matches in {message}")
            code = m.group(1)
            json_string = m.group(2)
            if code == "0":
                name = "0 open"
            elif code == "3":
                name = "3 heartbeat"
            elif code == "40":
                name = "40 message ok"
            elif code == "42":
                # this is rather specific to our use case. Some messages contain an originating timestamp,
                # and we use that to calculate the delay & report it as locust response time
                # see it as inspiration rather than something you just pick up and use
                obj = json.loads(json_string)
                name = f"{code} {obj[0]} apiUri: {obj[1]['apiUri']}"
                if obj[1]["value"] != "":
                    description = obj[1]["value"]["draw"]["description"]
                    description_match = description_regex.search(description)
                    if description_match:
                        sent_timestamp = int(description_match.group(1))
                        current_timestamp = round(time.monotonic() * 1000)
                        response_time = current_timestamp - sent_timestamp
                    else:
                        # differentiate samples that have no timestamps from ones that do
                        name += "_"
                else:
                    name += "_missingTimestamp"
            else:
                print(f"Received unexpected message: {message}")
                continue
            self.environment.events.request_success.fire(
                request_type="WSR", name=name, response_time=response_time, response_length=len(message)
            )

    def send(self, body):
        if body == "2":
            action = "2 heartbeat"
        else:
            m = re.search(r'(\d*)\["([a-z]*)"', body)
            assert m is not None
            code = m.group(1)
            action = m.group(2)
            url_part = re.search(r'"url": *"([^"]*)"', body)
            assert url_part is not None
            url = re.sub(r"/[0-9_]*/", "/:id/", url_part.group(1))
            action = f"{code} {action} url: {url}"

        self.environment.events.request_success.fire(
            request_type="WSS", name=action, response_time=None, response_length=len(body)
        )
        logging.debug(f"WSS: {body}")
        self.ws.send(body)

    def sleep_with_heartbeat(self, seconds):
        while seconds >= 0:
            gevent.sleep(min(15, seconds))
            seconds -= 15
            self.send("2")
```

**Comment by cyberw** [comment]
Use the example as a starting point https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/socketio_ex.py

you are not supposed to copy the base class :)

**Comment by j2l** [comment]
Thank you @cyberw , I finally understood the way it works :sweat_smile: 
Ok, I pip installed the plugins.
Since I want to test my websocket, in miniconda/.../locust_plugins/users.py, I changed:
`self.ws = websocket.create_connection(f"wss://{ws_host}/socket.io/?EIO=3&transport=websocket")`
to
`self.ws = websocket.create_connection(f"wss://{ws_host}")`

I copied https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/socketio_ex.py to my locustfile.py
and run it
and visited http://0.0.0.0:8089/ to start the load test
... but nothing happen. No user is spawned.

Only warning is about the file size (but it was also present while testing simple GET and it was working):
```
[2021-03-02 08:54:34,641] pop-os/WARNING/locust.main: System open file limit '1024' is below minimum setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2021-03-02 08:54:34,641] pop-os/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2021-03-02 08:54:34,648] pop-os/INFO/locust.main: Starting Locust 1.4.3
[2021-03-02 08:54:39,191] pop-os/INFO/locust.runners: Spawning 50 users at the rate 10 users/s (0 users already running)...
```
my Pop!_OS is Ubuntu 20.04
locust 1.4.3

I guess I missed something :)

**Comment by cyberw** [comment]
My first thought is that locust is unable to connect to your host. Can you run it in the debugger or print something just before and just after create_connection?

**Comment by j2l** [comment]
```
print(ws_host)
        self.ws = websocket.create_connection(f"wss://{ws_host}")
        print(ws)
```
results in printing the host once after running and hanging there:
```
Starting Locust 1.4.3
[2021-03-02 11:18:45,902] pop-os/INFO/locust.runners: Spawning 50 users at the rate 10 users/s (0 users already running)...
REDACTED.com
```

**Comment by cyberw** [comment]
So `websocket` is unable to connect to your host. Most likely, this has nothing to do with locust or SocketIOUser.

**Comment by j2l** [comment]
I use the same computer and network, actually the REDACTED.com service is running from my LAN, no proxy.
I can see websocket connections from regular clients in real time from my server.

Hmmm, as I want to understand, I re-ran the quickstart example:
```
import time
from locust import HttpUser, task, between

class QuickstartUser(HttpUser):
    wait_time = between(1, 2.5)

    @task
    def hello_world(self):
        self.client.get("")
```
from the same install.
It totally works:
![image](https://user-images.githubusercontent.com/65325/109643041-ff42c500-7b53-11eb-83b2-7f30d26f4162.png)

I really don't understand what is blocking the websocket locust plugin.

**Comment by j2l** [comment]
Could I send you a private message withe the real domain for you to test?
I added REDACTED since it's a proptype server running from my home and I have to test it today for tomorrow presentation.

**Comment by j2l** [comment]
FIXED!
I just added the same ws path (already present in the locustfile.py, so I wrongly assumed it was added to the host passed) and now it reaches the server:
![image](https://user-images.githubusercontent.com/65325/109644470-cb689f00-7b55-11eb-8020-29d7f437714d.png)

I wonder why the path is present is the locustfile :)
Never mind, it's working!
Maybe adding a ping before to make sure the domain is responding might help the error code that should spawn :smile: 
I'm not into locust enough to know how to do it.

BTW, there are many other questions:
- Looking at the webmin in real-time, I noticed a different behavior than when I use regular clients, how to mimic websocket outgoing?
- How to add websocket and locust-plugins to work with the locust docker container?

**Comment by cyberw** [comment]
> I just added the same ws path (already present in the locustfile.py, so I wrongly assumed it was added to the host passed)

Great! I might change it so that it defaults to use the "main" host specified in locust parameters or on host attribute for WS as well (in my use case I also wanted to run http requests against a different domain, so it made sense to keep them separate)

> Looking at the webmin in real-time, I noticed a different behavior than when I use regular clients, how to mimic websocket outgoing?
> How to add websocket and locust-plugins to work with the locust docker container?

These are things you'll just have to figure out yourself, sorry :)
