### ISSUE TITLE
Use a global KafkaProducer instead of creating one for each user

### ISSUE THREAD

**Issue by shubhendumadhukar** [SvenskaSpel/locust-plugins#36]
This is not exactly an issue, but an observation/a suggestion with reference to the [Kafka](https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/users/kafka.py) user.

Do you think it will make more sense to have the end user create a producer globally in their script and pass it in to the KafkaUser, instead of creating one for each instance of User? I was thinking something on these lines:

Instead of 
`bootstrap_servers: str = None` @ [kafka.py#L10](https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/users/kafka.py#L10)

if we had 
`producer: Producer = None`

It might make the code more optimised from a performance standpoint.

**Comment by cyberw** [comment]
I think it depends. In most cases it probably does make sense to have a single producer, but other times you may want to simulate separate producers with their own connection. 

But the performance impact should be minimal anyway. Not sure if it is a big issue.

**Comment by shubhendumadhukar** [comment]
Makes sense. I guess it depends on very specific use cases.

Thanks!
