### ISSUE TITLE
locust + timescaledb integration on new timescaledb versions

### ISSUE THREAD

**Issue by nemmeviu** [SvenskaSpel/locust-plugins#38]
Masters, please look this:

I'm try to run the locust+timescaledb integration using the timescale_schema.sql.
"to me" only work on docker image timescale/timescaledb:1.3.1-pg11-bitnami (bitnami or not, but version 1.3.1)

QUESTION: What's is my fail to load `timescale_schema.sql ` on new versions like timescale/timescaledb:2.1.0-pg13?

My step-by-step:

locust + timescaledb
====================

Step by step to create a timescaledb and locust integration.

## Official links:
* https://github.com/SvenskaSpel/locust-plugins/ [1]
* https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/timescale_listener_ex.py [2]
* https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/timescale_schema.sql [3]
* https://github.com/SvenskaSpel/locust-plugins/issues/11 [4]

## timescaledb docker image

* timescale/timescaledb:1.3.1-pg11-bitnami

## Steps to deploy

Create a database
```
> psql -U postgres -h 127.0.0.1
# create database locust;
# \c locust
# CREATE EXTENSION IF NOT EXISTS timescaledb;
```

Populate a locust database
```
> psql -U postgres -d locust -f ~/timescale_schema.sql -h 127.0.0.1
```

Remove a TRIGGER on request
```
> psql -U postgres -d locust -h 127.0.0.1
locust=# DROP TRIGGER ts_insert_blocker ON public.request;
```

**Comment by nemmeviu** [comment]
Removing kubernetes steps, not necessary for this issue.

**Comment by cyberw** [comment]
> "to me" only work on docker image timescale/timescaledb:1.3.1-pg11-bitnami 

I’m sorry, but I dont understand what you are saying. Please try to make it more clear, and add any error message you might have.
