### ISSUE TITLE
CCN client for Locust

### ISSUE THREAD

**Issue by josecastillolema** [SvenskaSpel/locust-plugins#5]
Hi @cyberw !

Hope to find you well.
I have developed a simple CCN-plugin for Locust (https://github.com/josecastillolema/locust-ccnclient).
Do you think it would be interesting for me to open a pull request to integrate it into locust-plugins?

Thanks,
Jose

**Comment by cyberw** [comment]
Hi! I would love to get a PR!

Please put it in its own subdirectory and provide an example in /examples

Is ccnlite a package that exists as a pypi package? If so, add it to setup.py.

**Comment by cyberw** [comment]
A PR is still welcome, but I'm closing the ticket for now.
