### ISSUE TITLE
Using plugin with locust==1.6.0

### ISSUE THREAD

**Issue by zz2014** [SvenskaSpel/locust-plugins#53]
Hi, Thanks for providing the plugin. 
I am trying to use the `-i` add-on for the command line. 
However, this command cannot be recognized by locust: 
```
locust: error: unrecognized arguments: -i
```

I ran `locust -f locustfile-that-imports-locust_plugins.py --help` as well but it also gives only hints on the commands from the locust. 
Am I missing some configuration?

**Comment by cyberw** [comment]
Does your locustfile-that-imports-plugins.py actually import locust-plugins?
