### ISSUE TITLE
Selenium server URL

### ISSUE THREAD

**Issue by asaph96** [SvenskaSpel/locust-plugins#55]
How do I set another URL for the selenium server besides the `"127.0.0.1:4444"` default one?

I was trying to run a docker-compose project but didn't found on the documentation how to pass my selenium-hub container's IP address to the WebdriverUser. I've tried to change the `command_executor` property, but with no success.

**Comment by cyberw** [comment]
I guess there isnt really any way to control that at the moment. Maybe add that as a setting on the WebdriverUser class?

**Comment by asaph96** [comment]
I think that would be nice to control it via WebdriverUser since its a wrapper to the Webdriver lib

**Comment by cyberw** [comment]
If you make a PR I will approve it.

**Comment by jmfiaschi** [comment]
Hello, can you reopen the issue and merge my modification if it's good for you ?

**Comment by cyberw** [comment]
The build is failing for your PR (code formatting). Fix it by running `black` and I’ll have another look!

**Comment by jmfiaschi** [comment]
Yes thank you, now it's good :)

**Comment by jmfiaschi** [comment]
Any news ? :) Tell me if I miss something

**Comment by cyberw** [comment]
Sorry, I thought I had already merged :)
