### ISSUE TITLE
Catch pkill and killall exceptions on WebdriverUser

### ISSUE THREAD

**Issue by asaph96** [SvenskaSpel/locust-plugins#56]
When experimenting with the package, I've found that when running a containerized worker with locust-plugins, some images would need to install `psmisc` since they didn't have `killall` command available. Thinking a bit, in any case, the termination bit would not be useful because running containerized would mean that probably I would be running a selenium server in a container as well. 

Maybe putting that part in a try-except statement could prevent future headaches for containerized/non-Unix systems.

**Comment by cyberw** [comment]
Makes sense. Can you make a PR? Log an info level message saying the processes could not be killed.

**Comment by jmfiaschi** [comment]
I add in the docker python image : 
```
apt-get update
apt-get install -y librdkafka-dev psmisc
```
