### ISSUE TITLE
Docker image with locust-plugin

### ISSUE THREAD

**Issue by sebader** [SvenskaSpel/locust-plugins#58]
First of all a big thank you for those great plugins!
This is not an issue but more of an FYI: Since I couldn't find another existing docker image which is based on vanilla locust image and includes your plugins, I just created one myself and published on dockerhub: https://github.com/sebader/locust-with-plugins

If there is another maintained version on dockerhub already, I'm happy to remove mine again

**Comment by cyberw** [comment]
You're welcome :) 

Cool! There's no other maintained version. I guess the appropriate way would be to include the locustfile in *this* repo. But I'm not sure I can be bothered :)

**Comment by sebader** [comment]
I guess you mean to include the *Dockerfile* in this repo?! happy to contribute it here, if you like. My repo basically only holds the dockerfile and a GitHub Action workflow to build and push the image to Dockerhub

**Comment by sebader** [comment]
I dont see a 2.0.0 tagged docker image yet - looks like *latest* might be it but I'm not sure

**Comment by cyberw** [comment]
ah, yes, sorry, *Dockerfile* :P 

Right now locust-plugins doesnt even have build automation, I just push directly to pypi.

**Comment by cyberw** [comment]
> I guess you mean to include the _Dockerfile_ in this repo?! happy to contribute it here, if you like. My repo basically only holds the dockerfile and a GitHub Action workflow to build and push the image to Dockerhub

Huh, something must have gone wrong with the build, "latest" is 2.0.0b3... I'll have a look..
