### ISSUE TITLE
Incorrect locustio requirement

### ISSUE THREAD

**Issue by MattFisher** [SvenskaSpel/locust-plugins#6]
`setup.py` requires `locustio>=1.0` but the latest version is only 0.14.5

https://github.com/SvenskaSpel/locust-plugins/blob/5b8613fd6acfc6525a0b27182cb98b07fab61ee2/setup.py#L39

**Comment by cyberw** [comment]
That is intentional (but temporary). If you want to use a git master version of locust-plugins right now you need to download locust from git, adjust its version to 1.0, and install it first.

**Comment by MattFisher** [comment]
Gotcha! Once I realised the master version of locust-plugins wasn't compatible with locustio 0.14.5 I went hunting around trying to work out what version it was working with, but got confused and gave up.
You seem to have been working on a lot of stuff recently that I'd find very useful, particularly the debug plugin.

**Comment by cyberw** [comment]
Thanks! I'll leave this ticket open until locust 1.0 is released in case someone else has the same issue.

**Comment by cyberw** [comment]
fixed (right now depending on pre-release/beta version)
