### ISSUE TITLE
Is the HTTP3/quic protocol supported

### ISSUE THREAD

**Issue by rory-wang** [SvenskaSpel/locust-plugins#60]
Whether the QUIC service can use Locust?

**Comment by rory-wang** [comment]
There are examples?

**Comment by cyberw** [comment]
It is not supported (because as far as i can tell, [requests](https://docs.python-requests.org/en/master/) doesnt support it). If you find a gevent-friendly library (not asyncio) that can do QUIC you should be able to build it though.
