### ISSUE TITLE
TimescaleDB plugin doesn't work on Windows

### ISSUE THREAD

**Issue by klott** [SvenskaSpel/locust-plugins#61]
Line 65 of listeners.py has a git check that includes a grep call, that Windows does not have installed by default, causing an error.
Why does this plugin need to check for a git repo in the first place?
Should be wrapped in a try/catch block at a minimum.

**Comment by cyberw** [comment]
Yes, please make a PR. Not sure it will work very well on windows anyway, but it is worth a shot.
