### ISSUE TITLE
Interested in a PR For MLLP/Socket Based Protocols?

### ISSUE THREAD

**Issue by dixonwhitmire** [SvenskaSpel/locust-plugins#72]
Hello,

I work within the health care industry and am interested in a contributing a new user class, MllpUser, to locust-plugins to support load testing clinical system throughput. The mllp protocol is based on the [HL7 standard](https://www.hl7.org/implement/standards/product_brief.cfm?product_id=55) .  The standard supports a socket based messaging exchange, and is (at least in the US), the primary means of exchanging clinical data. So this could potentially be useful to other developers working within health-care.

The messaging format used within the mllp protcol is rather simple. Each message is enclosed within a block.
```
<0x0B>  [start block 1 byte]
datadatadatadata..etc [variable data]
<0x1C> [end block 1 byte]
 <0x0D> [carriage return 1 byte]
```

Communication with a server is blocking/synchronous. A client has to wait for a server ACK before additional messages may be sent.

If you think this is something which could be a good addition to the repository, I will be happy to work on a PR. I could try to make things more generic and parameterize some of the "MLLP" spec, if you would prefer to have a "SockerUser" which could be fine tuned for different use-cases through configuration.

Thanks!

Dixon

**Comment by cyberw** [comment]
I think that would be very interesting indeed! A configurable SocketUser base class would be really nice!

**Comment by dixonwhitmire** [comment]
Thanks @cyberw - I will get started on this next week, once I get a development environment setup.

**Comment by dixonwhitmire** [comment]
Hi @cyberw - My priorities have changed a bit at work, so it may be a few weeks before I can get to this PR. 
Thanks!

**Comment by cyberw** [comment]
No problem!
