### ISSUE TITLE
Timeline plugin example

### ISSUE THREAD

**Issue by jacastaneda** [SvenskaSpel/locust-plugins#73]
Hello community,

is there any example on how to integrate the Timeline plugin for grafana dashboards?, I am trying to integrate that plugin but I am not sure if there is something to include in the python locust file, because the charts are showing blank,

I will really appreciate any help, thanks!

**Comment by cyberw** [comment]
All you need to do is import locus_plugins in your locustfile and add --timescale to the command line.

**Comment by jacastaneda** [comment]
Great, I was missing the postgres ENV vars so locust could not connect to the postgres instance, that is why the dashboard was blank, thanks @cyberw
