### ISSUE TITLE
How to set the Postgres env variable for TimescaleListener

### ISSUE THREAD

**Issue by ashanmuga** [SvenskaSpel/locust-plugins#77]
I am trying to set the env variable for Postgres credentials like below, 
 `**locust --timescale --headless -f LocustScript.py --pghost=localhost --pguser=admin --pgpassword=admin`
Getting the following error. 

>  fe_sendauth: no password supplied

I tried below method also.
```
**@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    TimescaleListener(env=environment, testplan="timescale_listener_ex", target_env="myTestEnv",PGPASSWORD="admin")
```
How can I set env variable?

_Originally posted by @ashanmuga in https://github.com/SvenskaSpel/locust-plugins/issues/18#issuecomment-1062289319_

**Comment by cyberw** [comment]
There was a bug, so only env var (PGPASSWORD) worked. Try now with the latest version! (2.5.6)

**Comment by ashanmuga** [comment]
Thanks, Now I am seeing TimescaleListener is removed, how can I invoke my own postgresDB and send locust success results to Postgres.

**Comment by cyberw** [comment]
Its not removed, just renamed & reworked. Follow the instructions here https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/timescale

**Comment by cyberw** [comment]
And use your first approach, not the second one.

**Comment by cyberw** [comment]
Doh! I had the same error for pghost & pguser. Also added --pgport and --pgdatabase while I was at it... Try it now (2.5.9)

**Comment by ashanmuga** [comment]
Thanks for fixing this. Now I am not getting any error. Not sure its connected to DB or not. locust stats not sent to DB. even I give wrong password while running command, no error thrown. Also if I want to send my success stats to my own DB, do I need to override any method in my locust file? I am following the instructions here,[https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/timescale](https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/timescale), but I want send locust results to my own DB and Grafana not needed. How can I do that using this plugin

**Comment by cyberw** [comment]
Sorry, thats all the time I have for now. If you want to, then keep digging and send me some more details (e.g. Is the grafana link being printed etc)

**Comment by ashanmuga** [comment]
I am looking to send locust result statistics to my own Postgres DB, this is the only part I am trying to do. Reason behind that, we want to store all the historical data of locust results to compare against.
