### ISSUE TITLE
Listener plugin performance to be improved with batching requests to timescaleDB

### ISSUE THREAD

**Issue by Sha90** [SvenskaSpel/locust-plugins#8]
Hi,
Thanks for the plugins, I was experimenting with your listener plugin and timescale db in docker container. My test script was doing 3000 get requests per second, and inserts were not performant with plugin. 

My Observations:
1. with triggers ts_insert_blockers, updates were not going through the DB. so I dropped the triggers and updates were fine.
2. locust seems to open 6 connections to timescale db, but only one is used, as below ps | grep output.
3. with 3000 requests per second, grafana was not able to show results in real time, looking at the timescaleDB documentation, batched updates are faster in timescale db while individual updates suffer with performance issues.
4. I don't think create ....chunk queries necessary in sql schema file. could you please confirm.
once again, thank you.

70 17906 3577 1 11:16 ? 00:00:00 postgres: postgres locust
172.17.0.1(41684) INSERT
70 17907 3577 0 11:16 ? 00:00:00 postgres: postgres locust
172.17.0.1(41688) idle
70 17908 3577 0 11:16 ? 00:00:00 postgres: postgres locust
172.17.0.1(41692) idle
70 17909 3577 0 11:16 ? 00:00:00 postgres: postgres locust
172.17.0.1(41696) idle
70 18469 3577 1 11:16 ? 00:00:00 postgres: postgres locust
172.17.0.1(42326) idle
70 18653 3577 0 11:17 ? 00:00:00 postgres: postgres locust
172.17.0.1(42398) idle
root 18655 27576 0 11:17 pts/2 00:00:00 grep --color=auto locust

**Comment by cyberw** [comment]
Hi! sorry for not responding, I think I started writing something but then forgot to send it.

1. Not sure what that is but great :)
2. I was getting errors for concurrently updating the request, testrun, events and users tables so I gave them dedicated connections. this isnt intended to optimize writing requests, just a hack to avoid getting concurrency errors. There should be 4 connections I think? Maybe opening multiple connections writing to the requests table would improve performance.
3. execute_values should be faster than execute_batch (as execute_batch actually does individidual inserts "under the hood"). but maybe you are talking about a different kind of batch? Just to be clear: are you having issues showing the results in grafana or inserting them into timescale?
4. That was done by timescale, not by me, so I dont want to change them unless there is a reason...

**Comment by cyberw** [comment]
On second thought, I'll keep this open. Maybe we'll want to do some optimizations at some point and it is nice to give some background to people encountering similar issues.

**Comment by micsjo** [comment]
Dumping the timescale tables for creation will not work. timescale creates the shards and indexes when it sets up a table for time series writes.

It's called creating a hypertable in timescale terminology.

[Please read the docs for this.](https://docs.timescale.com/latest/getting-started/creating-hypertables)

When this is done correctly and timescale is installed properly locust should use execute_values to write data or "batch" writing.

Then timescale has no problems writing very large amounts of time series data.

Since it is sql it is a bit picky and the amount of code for data formatting can be verbose.

**Comment by cyberw** [comment]
@micsjo Huh?
