### ISSUE TITLE
Local Grafana TestRuns Page Hyperlink to TestRun is Broken

### ISSUE THREAD

**Issue by chy8803** [SvenskaSpel/locust-plugins#81]
### Describe the bug
Local Grafana TestRuns Page Hyperlink to TestRun is Broken
<img width="1254" alt="Screen Shot 2022-03-28 at 11 28 18 PM" src="https://user-images.githubusercontent.com/20734659/160549082-3ecb452a-0da4-4cac-a79d-ab579cf5c86c.png">

### Expected behavior
When clicking on a testrun in testruns table page, the Hyperlink should go to
http://localhost:3000/d/qjIIww4Zz/locust?orgId=1&var-testplan=*****&from=1648534349103&to=1648534409375

### Actual behavior
https://grafana.internt.test.svenskaspel.se/d/qjIIww4Zz/locust?orgId=1&var-testplan=*****&from=1648534349103&to=1648534409375
It's having `https://grafana.internt.test.svenskaspel.se `instead of `http://localhost:3000`.

<img width="1009" alt="Screen Shot 2022-03-28 at 11 28 52 PM" src="https://user-images.githubusercontent.com/20734659/160547767-25f38c90-a8e0-4755-bcdc-ba0f677af869.png">

### Steps to reproduce
Always reproduce-able on local env

### Environment

- OS: MacOS
- Python version: Python 3.9.10
- Locust version: locust 2.8.5 locust-plugins 2.6.1
- Locust command line that you ran: `locust --config=master.conf`
- Locust file contents (anonymized if necessary): 
### locustfile.py
```
from locust import HttpUser, TaskSet, task, between, events
import os
import locust_plugins
from locust_plugins import listeners
import locust.env
import requests

os.environ["USER"] = "****"

@events.init.add_listener
def on_locust_init(environment, **_kwargs):
	environment.parsed_options.grafana_url = "http://localhost:3000/d/qjIIww4Zz?"
	listeners.Timescale(env=environment)

class LocalTester(HttpUser):
	wait_time = between(1, 2)
	host = "http://localhost:5001"
	@task(1)
	class test(TaskSet):
		@task
		def test1(self):
			self.client.get("/test1")
		@task
		def test2(self):
			self.client.post("/test2")
		@task
		def test3(self):
			self.client.post("/test3")
```

### master.conf in current directory
```
test-env = ***
test-version = 22.1
description = "Testing ****"
override-plan-name = *****
grafana-url = http://localhost:3000/d/qjIIww4Zz?
headless = true
users = 48
spawn-rate = 5
run-time = 1m
locustfile = locustfile.py
html=report.html
csv=stats
pguser = "postgres"
pgpassword = "password"
```

**Comment by cyberw** [comment]
Thanks for reporting. Should be fixed now (in 2.6.2, should be on pypi in a couple minutes)

**Comment by chy8803** [comment]
https://github.com/SvenskaSpel/locust-plugins/blob/e6d238834a5be356477a4222207f9107d971cb11/locust_plugins/dashboards/docker-compose.yml#L21
current tag for cyberw/locust-grafana in docker-compose.yml under the master branch is still 1.

**Comment by cyberw** [comment]
Doh. Try 2.6.3 (available in a couple minutes)

**Comment by cyberw** [comment]
Should work now.
