### ISSUE TITLE
Question about timescale DB initialization

### ISSUE THREAD

**Issue by Atmaks** [SvenskaSpel/locust-plugins#85]
Hello! First, thank you for taking the time to publish this project for the benefit of programming community! I'm not sure how much time it would take me to connect Locust to Grafana without it.

There's just something I couldn't understand in my own. IIUC, `timescale_schema.sql` is an initialization file meant to prepare Postgres DB for recieving data from Locust. I understand why you set some DB settings there, as well as create the tables. But what are "_hyper" tables for? To me they look like a forgotten part of an SQL dump from a running installation. I removed all of them from the file and managed to successfully run a small load test (and view the results in Grafana). Could you please clarify the issue?

**Comment by cyberw** [comment]
Hypertables are part of Timescale https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/

There's probably another (maybe better) way to create them, and maybe they will even be created by Timescale if they dont exist (and thus can be removed from the schema), but I dont know and I'm too lazy to investigate :)

I'd suggest you leave them in, but whatever works for you :)

**Comment by Atmaks** [comment]
Thank you for a quick and detailed response! 

In my case they weren't created automatically (at least they aren't shown in `psql \dt`). No clue why the setup is working without them. Moreover, the docs say they require non-standard SQL function calls, none of which are present in the SQL file. I'll chalk it up to computer magic.

In case you were wondering, I removed `hyper`-s because I copied your Docker configuration into my own project and modified it heavily (Grafana provisioning instead of API etc.) for some more control.

Anyway, my question was answered, so I'm closing the issue.

**Comment by cyberw** [comment]
how did you end up doing grafana provisioning? I looked into it but never got it working...

**Comment by cyberw** [comment]
also, if no hypertables are being created you may have ended up with a "regular" postgres table. That will probably work nicely for most cases, but not be as performant as a hypertable.

**Comment by Atmaks** [comment]
> how did you end up doing grafana provisioning? I looked into it but never got it working...

Well, my setup is really simple, we don't need anything distributed, and the target host is a (relatively) small corporate web-portal. I coudn't find a simple way to import dashboards from grafana.com and so ended up downloading JSON into project files. This is my directory structure:
```
├── compose.yml
├── grafana_config
│   ├── grafana.ini
│   └── provisioning
│       ├── dashboards
│       │   ├── locust_board.yml
│       │   ├── locust-requests-table_rev2.json
│       │   └── locust_rev11.json
│       └── datasources
│           └── locust_ds.yml
├── locust
│   └── Dockerfile
├── mnt
│   └── locust
│       ├── load_users.py
│       ├── locustfile.py
│       └── __pycache__
│           └── locustfile.cpython-39.pyc
├── timescale
│   ├── Dockerfile
│   └── timescale_schema.sql
```

Grafana configuration is simply transplanted into the container with a bind volume:
```
volumes:
      ...
      - ./grafana_config:/etc/grafana
```
The `.yml` files in `grafana_conf` are described [here](https://grafana.com/docs/grafana/latest/administration/provisioning). I copied the values from the JSON that you send to Grafana API in there. One caveat is that I had to hard-code the name of the data-source, since dashboard JSON does not support env-variables expansion.

I'm not even sure if this will be the production setup going forward. My goal was to have as much configuration and setup done upfront as possible, so I wouldn't have to tweak anything past launching Compose.



> also, if no hypertables are being created you may have ended up with a "regular" postgres table. That will probably work nicely for most cases, but not be as performant as a hypertable.

Thank you for the warning. I'll try to transform the tables into hypertables and see if it still works as before.

**Comment by cyberw** [comment]
Cool, thanks for the info!

**Comment by viginti23** [comment]
> 
> Thank you for the warning. I'll try to transform the tables into hypertables and see if it still works as before.
@Atmaks how did it work after all? :)

**Comment by Atmaks** [comment]
I don't remember the details, but I believe it worked in a small test run.
The task was canceled so I never got to see how it works in a real load
testing environment.

чт, 24 нояб. 2022 г., 12:37 Michał Zaród ***@***.***>:

**Comment by cyberw** [comment]
We run massive tests all the time and I just noticed that our hypertables were broken as well :) I havent had any issues.
