### ISSUE TITLE
why kafkauser produce messages quite slowly?

### ISSUE THREAD

**Issue by mangox** [SvenskaSpel/locust-plugins#95]
![1](https://user-images.githubusercontent.com/12643640/190674473-fc26d2f5-6eaf-4fe4-aaa8-71603698ce41.png)

Look at above image.
The kafka user only wrote about 110 qps, it's too slow...

**Comment by mangox** [comment]
I add some timing logs. it takes 8ms to send one message.
get message elapsed 0.0001037493348121643
send message elapsed 0.00840084906667471

I know kafka user using high-performance confluence_kafka and it supports 25000 writes/s in same machine in another test.

**Comment by cyberw** [comment]
KafkaUser calls self.producer.poll() after each send. Probably we should make that optional. PRs welcome…

**Comment by mangox** [comment]
Thank you for reply. I also notice that. I just try to extend the KafkaClient now.

**Comment by mangox** [comment]
I use poll(0) which suggested in kafka_ex.py. it's also working.

**Comment by cyberw** [comment]
Yea, probably having it in KafkaUser is just a bug.
