### ISSUE TITLE
locust response on grafana dashboard

### ISSUE THREAD

**Issue by Malleswari0413** [SvenskaSpel/locust-plugins#99]
Hi Team,
 I have gone through the locust-plugins doc and installed the grafana and postgres as a datasource but couldnt able add the data into it.i see the  locust-plugins done some of sql queries but i couldnt able to understand.
 For example:which locust py file we need to run to see the end to end flow
 required details:
 1.locust.py the main api/web apis file
 2.To monitor results in grafana which file we should run
 3.run line command 
 If anyone provide the above details it can help me to explore on locust
 Thanks in advance.

**Comment by cyberw** [comment]
https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/dashboards#setup
